/**
 * GİRİŞİMBEE MASTER 33 SEKTÖR VE NACE REFERANS VERİTABANI
 * Tüm 4 kokpit modülünde (Lokasyon Radarı, Bütçe Asistanı, Hukuk, Hibe)
 * kullanılan meslek havuzu bu merkezi kaynaktan alfabetik (A-Z) olarak sıralanır.
 */

export interface MasterSectorDefinition {
  id: string;
  name: string;
  emoji: string;
  categoryGroup: 'Finans & Hizmet' | 'Yeme - İçme' | 'Kişisel Bakım & Sağlık' | 'Perakende & Zanaat';
  naceCode: string;
  naceDescription: string;
  defaultM2: number;
  statutoryCapital: number;
  isKosgebEligible: boolean;
  kosgebCategory: 'Geleneksel Girişimci' | 'İleri Girişimci (Teknoloji/İmalat)';
  competitorPoiCategory: 'retail' | 'food' | 'service';
  primaryAuthority: string;
}

export const MASTER_SECTORS_LIST: MasterSectorDefinition[] = [
  // 1. A
  {
    id: 'dis-klinigi',
    name: 'Ağız & Diş Sağlığı Polikliniği',
    emoji: '🦷',
    categoryGroup: 'Kişisel Bakım & Sağlık',
    naceCode: '86.23.01',
    naceDescription: 'Özel Diş Hekimliği Faaliyetleri ve Ağız Diş Sağlığı Poliklinikleri',
    defaultM2: 110,
    statutoryCapital: 500000,
    isKosgebEligible: true,
    kosgebCategory: 'İleri Girişimci (Teknoloji/İmalat)',
    competitorPoiCategory: 'service',
    primaryAuthority: 'T.C. Sağlık Bakanlığı & Türk Dişhekimleri Birliği (TDB)',
  },
  // 2. B
  {
    id: 'butik-giyim',
    name: 'Butik & Giyim Mağazası',
    emoji: '👗',
    categoryGroup: 'Perakende & Zanaat',
    naceCode: '47.71.01',
    naceDescription: 'Belirli Bir Mala Tahsis Edilmiş Mağazalarda Giyim Eşyalarının Perakende Ticareti',
    defaultM2: 60,
    statutoryCapital: 50000,
    isKosgebEligible: true,
    kosgebCategory: 'Geleneksel Girişimci',
    competitorPoiCategory: 'retail',
    primaryAuthority: 'İlçe Belediyesi & Ticaret/Esnaf Odası',
  },
  // 3. Ç
  {
    id: 'cicekci-botanik',
    name: 'Çiçekçi & Botanik Tasarım Atölyesi',
    emoji: '💐',
    categoryGroup: 'Perakende & Zanaat',
    naceCode: '47.76.01',
    naceDescription: 'Çiçek, Bitki, Tohum ve Gübre Perakende Ticareti',
    defaultM2: 45,
    statutoryCapital: 50000,
    isKosgebEligible: true,
    kosgebCategory: 'Geleneksel Girişimci',
    competitorPoiCategory: 'retail',
    primaryAuthority: 'İlçe Belediyesi & Çiçekçiler Esnaf Odası',
  },
  // 4. Ç
  {
    id: 'cigkofte-subesi',
    name: 'Çiğköfteci & Fast Food Şubesi',
    emoji: '🌯',
    categoryGroup: 'Yeme - İçme',
    naceCode: '56.10.08',
    naceDescription: 'Çiğköfte, Dürüm ve Hızlı Yiyecek Hazırlama ve Satış Faaliyetleri',
    defaultM2: 35,
    statutoryCapital: 50000,
    isKosgebEligible: true,
    kosgebCategory: 'Geleneksel Girişimci',
    competitorPoiCategory: 'food',
    primaryAuthority: 'İl/İlçe Tarım ve Orman Müdürlüğü & Belediye',
  },
  // 5. D
  {
    id: 'donerci-kebapci',
    name: 'Dönerci & Kebapçı Lokantası',
    emoji: '🥙',
    categoryGroup: 'Yeme - İçme',
    naceCode: '56.10.07',
    naceDescription: 'Döner, Kebap ve Sıcak Et Yemekleri Sunan Restoran Faaliyetleri',
    defaultM2: 80,
    statutoryCapital: 50000,
    isKosgebEligible: true,
    kosgebCategory: 'Geleneksel Girişimci',
    competitorPoiCategory: 'food',
    primaryAuthority: 'İl/İlçe Tarım ve Orman Müdürlüğü & Lokantacılar Odası',
  },
  // 6. E
  {
    id: 'eczane-medikal',
    name: 'Eczane & Medikal Ürünler',
    emoji: '💊',
    categoryGroup: 'Kişisel Bakım & Sağlık',
    naceCode: '47.73.01',
    naceDescription: 'Eczacılık Ürünlerinin Perakende Satışı (Eczaneler)',
    defaultM2: 65,
    statutoryCapital: 250000,
    isKosgebEligible: true,
    kosgebCategory: 'Geleneksel Girişimci',
    competitorPoiCategory: 'retail',
    primaryAuthority: 'T.C. Sağlık Bakanlığı TİTCK & Türk Eczacıları Birliği (TEB)',
  },
  // 7. E
  {
    id: 'emlak-gayrimenkul',
    name: 'Emlak & Gayrimenkul Danışmanlığı',
    emoji: '🏢',
    categoryGroup: 'Finans & Hizmet',
    naceCode: '68.31.01',
    naceDescription: 'Gayrimenkul Acentelerinin Faaliyetleri (Taşınmaz Ticareti)',
    defaultM2: 50,
    statutoryCapital: 100000,
    isKosgebEligible: true,
    kosgebCategory: 'Geleneksel Girişimci',
    competitorPoiCategory: 'service',
    primaryAuthority: 'T.C. Ticaret Bakanlığı (TTBS) & Emlakçılar Odası',
  },
  // 8. F
  {
    id: 'firin-unlu-mamuller',
    name: 'Fırın & Unlu Mamüller İmalathanesi',
    emoji: '🥖',
    categoryGroup: 'Yeme - İçme',
    naceCode: '10.71.01',
    naceDescription: 'Fırın Ürünleri İmalatı (Ekmek, pide, simit vb.)',
    defaultM2: 140,
    statutoryCapital: 200000,
    isKosgebEligible: true,
    kosgebCategory: 'İleri Girişimci (Teknoloji/İmalat)',
    competitorPoiCategory: 'food',
    primaryAuthority: 'Tarım ve Orman Bakanlığı & Fırıncılar Odası',
  },
  // 9. G
  {
    id: 'kuafor-guzellik',
    name: 'Güzellik Salonu, Kuaför & Estetik',
    emoji: '💇‍♀️',
    categoryGroup: 'Kişisel Bakım & Sağlık',
    naceCode: '96.02.01',
    naceDescription: 'Güzellik Salonlarının Faaliyetleri (Cilt bakımı, kuaförlük, epilasyon)',
    defaultM2: 75,
    statutoryCapital: 50000,
    isKosgebEligible: true,
    kosgebCategory: 'Geleneksel Girişimci',
    competitorPoiCategory: 'service',
    primaryAuthority: 'İlçe Belediyesi & Kuaförler ve Güzellik Uzmanları Odası',
  },
  // 10. H
  {
    id: 'hukuk-burosu',
    name: 'Hukuk & Avukatlık Bürosu',
    emoji: '⚖️',
    categoryGroup: 'Finans & Hizmet',
    naceCode: '69.10.01',
    naceDescription: 'Hukuki Danışmanlık ve Avukatlık Faaliyetleri',
    defaultM2: 60,
    statutoryCapital: 50000,
    isKosgebEligible: true,
    kosgebCategory: 'Geleneksel Girişimci',
    competitorPoiCategory: 'service',
    primaryAuthority: 'Türkiye Barolar Birliği (TBB) & İlgili İl Barosu',
  },
  // 11. K
  {
    id: 'kafe-kahve',
    name: 'Kafe & Nitelikli Kahve Dükkanı',
    emoji: '☕',
    categoryGroup: 'Yeme - İçme',
    naceCode: '56.30.02',
    naceDescription: 'Kahvehaneler, Özel Kahve Sunumu Yapan Kafeler ve İçecek Sunumu',
    defaultM2: 70,
    statutoryCapital: 100000,
    isKosgebEligible: true,
    kosgebCategory: 'Geleneksel Girişimci',
    competitorPoiCategory: 'food',
    primaryAuthority: 'İlçe Belediyesi & Tarım ve Orman Müdürlüğü',
  },
  // 12. K
  {
    id: 'kirtasiye-kitap',
    name: 'Kırtasiye, Kitap & Ofis Malzemeleri',
    emoji: '📚',
    categoryGroup: 'Perakende & Zanaat',
    naceCode: '47.62.01',
    naceDescription: 'Kitap, Kırtasiye ve Büro Malzemeleri Perakende Ticareti',
    defaultM2: 55,
    statutoryCapital: 50000,
    isKosgebEligible: true,
    kosgebCategory: 'Geleneksel Girişimci',
    competitorPoiCategory: 'retail',
    primaryAuthority: 'İlçe Belediyesi & Kitapçılar Esnaf Odası',
  },
  // 13. K (YENİ)
  {
    id: 'kres-gunduz-bakimevi',
    name: 'Kreş & Gündüz Bakımevi / Anaokulu',
    emoji: '👶',
    categoryGroup: 'Finans & Hizmet',
    naceCode: '88.91.01',
    naceDescription: 'Çocuk Gündüz Bakım Faaliyetleri (Kreş, anaokulu, gündüz bakımevi)',
    defaultM2: 220,
    statutoryCapital: 300000,
    isKosgebEligible: true,
    kosgebCategory: 'Geleneksel Girişimci',
    competitorPoiCategory: 'service',
    primaryAuthority: 'T.C. Aile ve Sosyal Hizmetler Bakanlığı / MEB',
  },
  // 14. K
  {
    id: 'kuru-temizleme',
    name: 'Kuru Temizleme & Terzi Hizmetleri',
    emoji: '👔',
    categoryGroup: 'Perakende & Zanaat',
    naceCode: '96.01.01',
    naceDescription: 'Çamaşırhane, Kuru Temizleme ve Giysi Onarım Hizmetleri',
    defaultM2: 45,
    statutoryCapital: 50000,
    isKosgebEligible: true,
    kosgebCategory: 'Geleneksel Girişimci',
    competitorPoiCategory: 'service',
    primaryAuthority: 'İlçe Belediyesi & Kuru Temizlemeciler Odası',
  },
  // 15. K (YENİ)
  {
    id: 'lojistik-kurye',
    name: 'Kurye Dağıtım & Şehir İçi Lojistik',
    emoji: '🛵',
    categoryGroup: 'Finans & Hizmet',
    naceCode: '53.20.09',
    naceDescription: 'Kurye ve Paket Dağıtım Faaliyetleri (Şehir içi hızlı teslimat)',
    defaultM2: 40,
    statutoryCapital: 100000,
    isKosgebEligible: true,
    kosgebCategory: 'Geleneksel Girişimci',
    competitorPoiCategory: 'service',
    primaryAuthority: 'T.C. Ulaştırma ve Altyapı Bakanlığı (P2/K1 Yetki Belgesi)',
  },
  // 16. L
  {
    id: 'lastik-servisi',
    name: 'Lastik, Jant & Hızlı Araç Servisi',
    emoji: '🛞',
    categoryGroup: 'Perakende & Zanaat',
    naceCode: '45.20.04',
    naceDescription: 'Motorlu Kara Taşıtlarının Lastik Onarımı, Değişimi ve Balans Ayarı',
    defaultM2: 90,
    statutoryCapital: 100000,
    isKosgebEligible: true,
    kosgebCategory: 'Geleneksel Girişimci',
    competitorPoiCategory: 'service',
    primaryAuthority: 'İlçe Belediyesi & Oto Sanatkarları Esnaf Odası',
  },
  // 17. M
  {
    id: 'muhasebe-smmm',
    name: 'Mali Müşavirlik & SMMM Bürosu',
    emoji: '📊',
    categoryGroup: 'Finans & Hizmet',
    naceCode: '69.20.01',
    naceDescription: 'Mali Müşavirlik, Muhasebe ve Vergi Danışmanlığı Faaliyetleri',
    defaultM2: 50,
    statutoryCapital: 50000,
    isKosgebEligible: true,
    kosgebCategory: 'Geleneksel Girişimci',
    competitorPoiCategory: 'service',
    primaryAuthority: 'TÜRMOB & İlgili İl SMMM Odası',
  },
  // 18. M (YENİ)
  {
    id: 'mimarlik-muhendislik',
    name: 'Mimarlık & Mühendislik Proje Ofisi',
    emoji: '📐',
    categoryGroup: 'Finans & Hizmet',
    naceCode: '71.11.01',
    naceDescription: 'Mimarlık Faaliyetleri ve Bina Proje Danışmanlık Hizmetleri',
    defaultM2: 55,
    statutoryCapital: 50000,
    isKosgebEligible: true,
    kosgebCategory: 'Geleneksel Girişimci',
    competitorPoiCategory: 'service',
    primaryAuthority: 'TMMOB Mimarlar Odası / İnşaat Mühendisleri Odası',
  },
  // 19. O
  {
    id: 'optik-magazasi',
    name: 'Optik Mağazası & Gözlükçü',
    emoji: '👓',
    categoryGroup: 'Kişisel Bakım & Sağlık',
    naceCode: '47.78.02',
    naceDescription: 'Gözlük, Lens ve Optik Ürünlerin Perakende Satışı',
    defaultM2: 45,
    statutoryCapital: 100000,
    isKosgebEligible: true,
    kosgebCategory: 'Geleneksel Girişimci',
    competitorPoiCategory: 'retail',
    primaryAuthority: 'T.C. Sağlık Bakanlığı & Türk Optisyen-Gözlükçüler Birliği (TOGB)',
  },
  // 20. O
  {
    id: 'oto-ekspertiz',
    name: 'Oto Ekspertiz & Muayene İstasyonu',
    emoji: '🔍',
    categoryGroup: 'Perakende & Zanaat',
    naceCode: '71.20.08',
    naceDescription: 'Motorlu Taşıtların Teknik Muayene, Dyno Test ve Ekspertiz Faaliyetleri',
    defaultM2: 120,
    statutoryCapital: 250000,
    isKosgebEligible: true,
    kosgebCategory: 'İleri Girişimci (Teknoloji/İmalat)',
    competitorPoiCategory: 'service',
    primaryAuthority: 'Türk Standardları Enstitüsü (TSE 13805) & Ticaret Bakanlığı',
  },
  // 21. O
  {
    id: 'oto-yikama',
    name: 'Oto Yıkama & Detailing Merkezi',
    emoji: '🚿',
    categoryGroup: 'Perakende & Zanaat',
    naceCode: '45.20.06',
    naceDescription: 'Otomobil Yıkama, Cilalama, Seramik Kaplama ve Benzeri Faaliyetler',
    defaultM2: 130,
    statutoryCapital: 100000,
    isKosgebEligible: true,
    kosgebCategory: 'Geleneksel Girişimci',
    competitorPoiCategory: 'service',
    primaryAuthority: 'İlçe Belediyesi & Su ve Kanalizasyon İdaresi (SKİ Deşarj İzni)',
  },
  // 22. P (YENİ)
  {
    id: 'tatlici-pastane',
    name: 'Pastane, Tatlıcı & Butik Fırın',
    emoji: '🍰',
    categoryGroup: 'Yeme - İçme',
    naceCode: '10.71.02',
    naceDescription: 'Pastane Ürünleri, Tatlı ve Pasta İmalatı ve Satışı',
    defaultM2: 75,
    statutoryCapital: 100000,
    isKosgebEligible: true,
    kosgebCategory: 'Geleneksel Girişimci',
    competitorPoiCategory: 'food',
    primaryAuthority: 'İl/İlçe Tarım ve Orman Müdürlüğü & Pastacılar Odası',
  },
  // 23. P
  {
    id: 'petshop-urunleri',
    name: 'Petshop & Veteriner Ürünleri',
    emoji: '🐾',
    categoryGroup: 'Perakende & Zanaat',
    naceCode: '47.76.02',
    naceDescription: 'Evcil Hayvanlar ile Bunların Mama ve Yemlerinin Perakende Satışı',
    defaultM2: 50,
    statutoryCapital: 50000,
    isKosgebEligible: true,
    kosgebCategory: 'Geleneksel Girişimci',
    competitorPoiCategory: 'retail',
    primaryAuthority: 'İlçe Belediyesi & İlçe Tarım Müdürlüğü',
  },
  // 24. P
  {
    id: 'pilates-yoga',
    name: 'Pilates, Yoga & Reformer Stüdyosu',
    emoji: '🧘‍♀️',
    categoryGroup: 'Kişisel Bakım & Sağlık',
    naceCode: '93.13.01',
    naceDescription: 'Fitness, Pilates ve Vücut Geliştirme Merkezleri Faaliyetleri',
    defaultM2: 90,
    statutoryCapital: 50000,
    isKosgebEligible: true,
    kosgebCategory: 'Geleneksel Girişimci',
    competitorPoiCategory: 'service',
    primaryAuthority: 'Gençlik ve Spor İl Müdürlüğü & Türkiye Cimnastik Federasyonu',
  },
  // 25. P (YENİ)
  {
    id: 'psikolojik-danismanlik',
    name: 'Psikolojik Danışmanlık & Terapi',
    emoji: '🧠',
    categoryGroup: 'Kişisel Bakım & Sağlık',
    naceCode: '86.90.14',
    naceDescription: 'Psikolog ve Aile Danışmanlığı Faaliyetleri (Tıp doktoru olmayanlarca)',
    defaultM2: 55,
    statutoryCapital: 50000,
    isKosgebEligible: true,
    kosgebCategory: 'Geleneksel Girişimci',
    competitorPoiCategory: 'service',
    primaryAuthority: 'İl Sağlık Müdürlüğü / Aile ve Sosyal Hizmetler İl Müdürlüğü',
  },
  // 26. R
  {
    id: 'restoran-lokanta',
    name: 'Restoran, Lokanta & Yemek Servisi',
    emoji: '🍽️',
    categoryGroup: 'Yeme - İçme',
    naceCode: '56.10.08',
    naceDescription: 'Lokantalar ve Restoranların Faaliyetleri (Oturarak servis yapılanlar)',
    defaultM2: 120,
    statutoryCapital: 150000,
    isKosgebEligible: true,
    kosgebCategory: 'Geleneksel Girişimci',
    competitorPoiCategory: 'food',
    primaryAuthority: 'Tarım ve Orman Bakanlığı & İlçe Belediyesi',
  },
  // 27. S
  {
    id: 'sigorta-acentesi',
    name: 'Sigorta Acentesi (SEDDK / Levha)',
    emoji: '🛡️',
    categoryGroup: 'Finans & Hizmet',
    naceCode: '66.22.01',
    naceDescription: 'Sigorta Acentelerinin ve Aracılarının Faaliyetleri',
    defaultM2: 45,
    statutoryCapital: 4149275, // 2026 SEDDK Tebliği
    isKosgebEligible: true,
    kosgebCategory: 'Geleneksel Girişimci',
    competitorPoiCategory: 'service',
    primaryAuthority: 'Sigortacılık ve Özel Emeklilik Düzenleme ve Denetleme Kurumu (SEDDK)',
  },
  // 28. S (YENİ)
  {
    id: 'surucu-kursu',
    name: 'Sürücü Kursu & MTSK Merkezi',
    emoji: '🚗',
    categoryGroup: 'Finans & Hizmet',
    naceCode: '85.53.01',
    naceDescription: 'Sürücü Kursu Faaliyetleri (Motorlu Taşıt Sürücüleri Kursu)',
    defaultM2: 140,
    statutoryCapital: 250000,
    isKosgebEligible: true,
    kosgebCategory: 'Geleneksel Girişimci',
    competitorPoiCategory: 'service',
    primaryAuthority: 'T.C. Millî Eğitim Bakanlığı (MEB Özel Öğretim Kurumları)',
  },
  // 29. S
  {
    id: 'market-bakkal',
    name: 'Süpermarket & Bakkal',
    emoji: '🛒',
    categoryGroup: 'Perakende & Zanaat',
    naceCode: '47.11.01',
    naceDescription: 'Bakkal ve Marketlerde Gıda, İçecek ve Tütün Perakende Ticareti',
    defaultM2: 85,
    statutoryCapital: 100000,
    isKosgebEligible: true,
    kosgebCategory: 'Geleneksel Girişimci',
    competitorPoiCategory: 'retail',
    primaryAuthority: 'İlçe Belediyesi & Bakkallar Esnaf Odası',
  },
  // 30. T
  {
    id: 'telefon-aksesuar',
    name: 'Telefon, Tablet & Bilişim Aksesuarı',
    emoji: '📱',
    categoryGroup: 'Perakende & Zanaat',
    naceCode: '47.42.01',
    naceDescription: 'Telekomünikasyon Teçhizatı, Telefon ve Aksesuar Perakende Satışı',
    defaultM2: 35,
    statutoryCapital: 50000,
    isKosgebEligible: true,
    kosgebCategory: 'Geleneksel Girişimci',
    competitorPoiCategory: 'retail',
    primaryAuthority: 'İlçe Belediyesi & İletişimciler Esnaf Odası',
  },
  // 31. V (YENİ)
  {
    id: 'veteriner-klinigi',
    name: 'Veteriner Kliniği & Hayvan Hastanesi',
    emoji: '🩺',
    categoryGroup: 'Kişisel Bakım & Sağlık',
    naceCode: '75.00.02',
    naceDescription: 'Evcil Hayvanlara Yönelik Veterinerlik Hizmetleri ve Klinik Faaliyetleri',
    defaultM2: 85,
    statutoryCapital: 200000,
    isKosgebEligible: true,
    kosgebCategory: 'İleri Girişimci (Teknoloji/İmalat)',
    competitorPoiCategory: 'service',
    primaryAuthority: 'Tarım ve Orman Bakanlığı & Türk Veteriner Hekimleri Birliği (TVHB)',
  },
  // 32. W (YENİ)
  {
    id: 'waffle-cikolata',
    name: 'Waffle & Butik Tatlıcı',
    emoji: '🧇',
    categoryGroup: 'Yeme - İçme',
    naceCode: '56.10.08',
    naceDescription: 'Waffle, Krep, Çikolata ve Butik Tatlı Hazırlama ve Satış Faaliyetleri',
    defaultM2: 45,
    statutoryCapital: 50000,
    isKosgebEligible: true,
    kosgebCategory: 'Geleneksel Girişimci',
    competitorPoiCategory: 'food',
    primaryAuthority: 'İl/İlçe Tarım ve Orman Müdürlüğü & Belediye',
  },
  // 33. Y
  {
    id: 'yazilim-ajans',
    name: 'Yazılım, SaaS & Dijital Ajans',
    emoji: '💻',
    categoryGroup: 'Finans & Hizmet',
    naceCode: '62.01.01',
    naceDescription: 'Bilgisayar Programlama Faaliyetleri (Sistem, web, yapay zeka, mobil uygulama)',
    defaultM2: 60,
    statutoryCapital: 50000,
    isKosgebEligible: true,
    kosgebCategory: 'İleri Girişimci (Teknoloji/İmalat)',
    competitorPoiCategory: 'service',
    primaryAuthority: 'Sanayi ve Teknoloji Bakanlığı & Bilişim İhracatçıları Birliği (HİB)',
  },

  // --- YENİ EKLENEN 22 MASTER SEKTÖR ---
  {
  "id": "bubble-tea-bar",
  "name": "Bubble Tea & Özel İçecek Barı",
  "emoji": "🧋",
  "categoryGroup": "Yeme - İçme",
  "naceCode": "56.30.02",
  "naceDescription": "Çay, Kahve, Meyve Suyu ve İçecek Sunan Mekanların Faaliyetleri",
  "defaultM2": 35,
  "statutoryCapital": 50000,
  "isKosgebEligible": true,
  "kosgebCategory": "Geleneksel Girişimci",
  "competitorPoiCategory": "food",
  "primaryAuthority": "İl/İlçe Tarım ve Orman Müdürlüğü & Belediye"
},
  {
  "id": "butik-burger",
  "name": "Butik Burger & Sokak Lezzetleri",
  "emoji": "🍔",
  "categoryGroup": "Yeme - İçme",
  "naceCode": "56.10.08",
  "naceDescription": "Fast-Food, Burger ve Hızlı Yiyecek Hazırlama ve Satış Faaliyetleri",
  "defaultM2": 65,
  "statutoryCapital": 50000,
  "isKosgebEligible": true,
  "kosgebCategory": "Geleneksel Girişimci",
  "competitorPoiCategory": "food",
  "primaryAuthority": "İl/İlçe Tarım ve Orman Müdürlüğü & Lokantacılar Odası"
},
  {
  "id": "dondurma-gelato",
  "name": "Artisan Dondurmacı & Gelato Barı",
  "emoji": "🍨",
  "categoryGroup": "Yeme - İçme",
  "naceCode": "56.10.05",
  "naceDescription": "Dondurma ve Diğer Soğuk Tatlıların İmalatı ve Satışı",
  "defaultM2": 40,
  "statutoryCapital": 50000,
  "isKosgebEligible": true,
  "kosgebCategory": "Geleneksel Girişimci",
  "competitorPoiCategory": "food",
  "primaryAuthority": "İl/İlçe Tarım ve Orman Müdürlüğü & Belediye"
},
  {
  "id": "kahvalti-borek-salonu",
  "name": "Kahvaltı & Serpme Börek Salonu",
  "emoji": "🍳",
  "categoryGroup": "Yeme - İçme",
  "naceCode": "56.10.01",
  "naceDescription": "Geleneksel Kahvaltı ve Sıcak Yemek Restoran Hizmetleri",
  "defaultM2": 90,
  "statutoryCapital": 50000,
  "isKosgebEligible": true,
  "kosgebCategory": "Geleneksel Girişimci",
  "competitorPoiCategory": "food",
  "primaryAuthority": "İl/İlçe Tarım ve Orman Müdürlüğü & Belediye"
},
  {
  "id": "corbaci-paca",
  "name": "Tarihi Gece Çorbacısı & Paça Salonu",
  "emoji": "🥣",
  "categoryGroup": "Yeme - İçme",
  "naceCode": "56.10.01",
  "naceDescription": "Geleneksel Çorba, Paça ve Gece Lokantacılığı Faaliyetleri",
  "defaultM2": 80,
  "statutoryCapital": 50000,
  "isKosgebEligible": true,
  "kosgebCategory": "Geleneksel Girişimci",
  "competitorPoiCategory": "food",
  "primaryAuthority": "İl/İlçe Tarım ve Orman Müdürlüğü & Belediye"
},
  {
  "id": "guzellik-lazer-merkezi",
  "name": "Güzellik & Lazer Epilasyon Merkezi",
  "emoji": "💄",
  "categoryGroup": "Kişisel Bakım & Sağlık",
  "naceCode": "96.02.03",
  "naceDescription": "Güzellik Salonlarının Faaliyetleri (Cilt bakımı, epilasyon, masaj vb.)",
  "defaultM2": 85,
  "statutoryCapital": 100000,
  "isKosgebEligible": true,
  "kosgebCategory": "Geleneksel Girişimci",
  "competitorPoiCategory": "service",
  "primaryAuthority": "İl Sağlık Müdürlüğü & Belediye Ruhsat Müdürlüğü"
},
  {
  "id": "nail-art-protez-tirnak",
  "name": "Nail Art & Protez Tırnak Stüdyosu",
  "emoji": "💅",
  "categoryGroup": "Kişisel Bakım & Sağlık",
  "naceCode": "96.02.04",
  "naceDescription": "Manikür, Pedikür ve Tırnak Tasarım Hizmetleri",
  "defaultM2": 40,
  "statutoryCapital": 50000,
  "isKosgebEligible": true,
  "kosgebCategory": "Geleneksel Girişimci",
  "competitorPoiCategory": "service",
  "primaryAuthority": "Kuaförler ve Manikürcüler Esnaf Odası & Belediye"
},
  {
  "id": "diyetisyen-beslenme-klinigi",
  "name": "Diyetisyen & Beslenme Danışmanlığı",
  "emoji": "🥗",
  "categoryGroup": "Kişisel Bakım & Sağlık",
  "naceCode": "86.90.17",
  "naceDescription": "Tıp Dışı Sağlık Danışmanlığı (Diyetisyen ve Beslenme Uzmanları)",
  "defaultM2": 45,
  "statutoryCapital": 50000,
  "isKosgebEligible": true,
  "kosgebCategory": "Geleneksel Girişimci",
  "competitorPoiCategory": "service",
  "primaryAuthority": "T.C. Sağlık Bakanlığı & Türkiye Diyetisyenler Derneği"
},
  {
  "id": "yeni-nesil-berber",
  "name": "Yeni Nesil Berber & Erkek Bakım Salonu",
  "emoji": "💈",
  "categoryGroup": "Kişisel Bakım & Sağlık",
  "naceCode": "96.02.01",
  "naceDescription": "Erkek Berberliği ve Saç Kesim Faaliyetleri",
  "defaultM2": 50,
  "statutoryCapital": 50000,
  "isKosgebEligible": true,
  "kosgebCategory": "Geleneksel Girişimci",
  "competitorPoiCategory": "service",
  "primaryAuthority": "Berberler ve Kuaförler Esnaf Odası & Belediye"
},
  {
  "id": "nalbur-yapi-market",
  "name": "Nalbur & Yapı Hırdavat Marketi",
  "emoji": "🔨",
  "categoryGroup": "Perakende & Zanaat",
  "naceCode": "47.52.01",
  "naceDescription": "Hırdavat, Boya, Tesisat ve Cam Mallarının Perakende Ticareti",
  "defaultM2": 120,
  "statutoryCapital": 50000,
  "isKosgebEligible": true,
  "kosgebCategory": "Geleneksel Girişimci",
  "competitorPoiCategory": "retail",
  "primaryAuthority": "Demirciler ve Hırdavatçılar Odası & Belediye"
},
  {
  "id": "kuyumcu-sarraf",
  "name": "Kuyumcu & Sarrafiye Mağazası",
  "emoji": "💍",
  "categoryGroup": "Perakende & Zanaat",
  "naceCode": "47.77.01",
  "naceDescription": "Belirli Bir Mala Tahsis Edilmiş Mağazalarda Altın ve Mücevher Perakende Ticareti",
  "defaultM2": 35,
  "statutoryCapital": 1000000,
  "isKosgebEligible": false,
  "kosgebCategory": "Geleneksel Girişimci",
  "competitorPoiCategory": "retail",
  "primaryAuthority": "T.C. Ticaret Bakanlığı & Kuyumcular Odası & MASAK"
},
  {
  "id": "zuccaciye-ev-esyalari",
  "name": "Züccaciye & Ev Eşyaları Mağazası",
  "emoji": "🍽️",
  "categoryGroup": "Perakende & Zanaat",
  "naceCode": "47.59.02",
  "naceDescription": "Çatal Bıçak Takımı, Mutfak Eşyası ve Porselen Perakende Ticareti",
  "defaultM2": 90,
  "statutoryCapital": 50000,
  "isKosgebEligible": true,
  "kosgebCategory": "Geleneksel Girişimci",
  "competitorPoiCategory": "retail",
  "primaryAuthority": "Ticaret Odası & Belediye"
},
  {
  "id": "dijital-baski-matbaa",
  "name": "Dijital Baskı & Matbaa Merkezi",
  "emoji": "🖨️",
  "categoryGroup": "Perakende & Zanaat",
  "naceCode": "18.12.01",
  "naceDescription": "Diğer Matbaacılık Faaliyetleri (Dijital, ofset, tabela, folyo)",
  "defaultM2": 70,
  "statutoryCapital": 50000,
  "isKosgebEligible": true,
  "kosgebCategory": "İleri Girişimci (Teknoloji/İmalat)",
  "competitorPoiCategory": "service",
  "primaryAuthority": "Matbaacılar Esnaf Odası & Belediye"
},
  {
  "id": "dil-okulu-kurs",
  "name": "Yabancı Dil Kursu & Sınav Hazırlık",
  "emoji": "📚",
  "categoryGroup": "Finans & Hizmet",
  "naceCode": "85.59.03",
  "naceDescription": "Dil ve Konuşma Becerileri Eğitimi Veren Özel Kurslar",
  "defaultM2": 160,
  "statutoryCapital": 100000,
  "isKosgebEligible": true,
  "kosgebCategory": "Geleneksel Girişimci",
  "competitorPoiCategory": "service",
  "primaryAuthority": "Milli Eğitim Bakanlığı (MEB) Özel Öğretim Kurumları Genel Müdürlüğü"
},
  {
  "id": "turizm-seyahat-acentesi",
  "name": "Turizm & Seyahat Acentesi (TÜRSAB)",
  "emoji": "✈️",
  "categoryGroup": "Finans & Hizmet",
  "naceCode": "79.11.01",
  "naceDescription": "Seyahat Acentesi Faaliyetleri (Ulaşım, konaklama, tur organizasyonu)",
  "defaultM2": 50,
  "statutoryCapital": 350000,
  "isKosgebEligible": true,
  "kosgebCategory": "Geleneksel Girişimci",
  "competitorPoiCategory": "service",
  "primaryAuthority": "Kültür ve Turizm Bakanlığı & TÜRSAB"
},
  {
  "id": "parti-cocuk-oyun-evi",
  "name": "Çocuk Oyun Evi & Doğum Günü Atölyesi",
  "emoji": "🎈",
  "categoryGroup": "Finans & Hizmet",
  "naceCode": "93.29.02",
  "naceDescription": "Çocuk Oyun Alanları, Softplay ve Eğlence Parkı Faaliyetleri",
  "defaultM2": 120,
  "statutoryCapital": 50000,
  "isKosgebEligible": true,
  "kosgebCategory": "Geleneksel Girişimci",
  "competitorPoiCategory": "service",
  "primaryAuthority": "İlçe Belediyesi Ruhsat ve Denetim Müdürlüğü & TSE"
},
  {
  "id": "oto-kiralama-rentacar",
  "name": "Oto Kiralama & Rent A Car Ofisi",
  "emoji": "🚘",
  "categoryGroup": "Finans & Hizmet",
  "naceCode": "77.11.01",
  "naceDescription": "Motorlu Kara Taşıtlarının Sürücüsüz Olarak Kiralanması (Rent A Car)",
  "defaultM2": 45,
  "statutoryCapital": 250000,
  "isKosgebEligible": true,
  "kosgebCategory": "Geleneksel Girişimci",
  "competitorPoiCategory": "service",
  "primaryAuthority": "T.C. Ticaret Bakanlığı & Emniyet Genel Müdürlüğü (KABİS)"
},
  {
  "id": "oto-yedek-parca",
  "name": "Oto Yedek Parça & Akü Satış",
  "emoji": "⚙️",
  "categoryGroup": "Perakende & Zanaat",
  "naceCode": "45.32.02",
  "naceDescription": "Motorlu Kara Taşıtlarının Parça ve Aksesuarlarının Perakende Ticareti",
  "defaultM2": 80,
  "statutoryCapital": 50000,
  "isKosgebEligible": true,
  "kosgebCategory": "Geleneksel Girişimci",
  "competitorPoiCategory": "retail",
  "primaryAuthority": "Ticaret Odası & Belediye"
},
  {
  "id": "dijital-pazarlama-ajansi",
  "name": "Dijital Pazarlama & Sosyal Medya Ajansı",
  "emoji": "📢",
  "categoryGroup": "Finans & Hizmet",
  "naceCode": "73.11.01",
  "naceDescription": "Reklam Ajanslarının Faaliyetleri (Dijital medya, sosyal medya, SEO)",
  "defaultM2": 60,
  "statutoryCapital": 50000,
  "isKosgebEligible": true,
  "kosgebCategory": "İleri Girişimci (Teknoloji/İmalat)",
  "competitorPoiCategory": "service",
  "primaryAuthority": "Ticaret Odası & Bilişim İhracatçıları Birliği (HİB)"
},
  {
  "id": "mobilya-dekorasyon",
  "name": "Butik Mobilya & Ev Dekorasyonu",
  "emoji": "🛋️",
  "categoryGroup": "Perakende & Zanaat",
  "naceCode": "47.59.01",
  "naceDescription": "Ev Mobilyalarının Perakende Ticareti",
  "defaultM2": 140,
  "statutoryCapital": 50000,
  "isKosgebEligible": true,
  "kosgebCategory": "Geleneksel Girişimci",
  "competitorPoiCategory": "retail",
  "primaryAuthority": "Mobilyacılar Odası & Ticaret Odası"
},
  {
  "id": "cilingir-anahtar",
  "name": "Çilingir & Güvenlik Kilit Atölyesi",
  "emoji": "🔑",
  "categoryGroup": "Perakende & Zanaat",
  "naceCode": "95.29.03",
  "naceDescription": "Kilit ve Anahtar Tamiri, Çilingirlik Hizmetleri ve Anahtar Çoğaltma",
  "defaultM2": 30,
  "statutoryCapital": 50000,
  "isKosgebEligible": true,
  "kosgebCategory": "Geleneksel Girişimci",
  "competitorPoiCategory": "service",
  "primaryAuthority": "Çilingirler ve Anahtarcılar Odası & İl Emniyet Müdürlüğü"
},
  {
  "id": "oto-tamir-mekanik",
  "name": "Oto Tamir & Mekanik Bakım Servisi",
  "emoji": "🔧",
  "categoryGroup": "Otomotiv & Sanayi",
  "naceCode": "45.20.01",
  "naceDescription": "Motorlu Kara Taşıtlarının Genel Bakım ve Onarım Hizmetleri (Mekanik, motor, fren)",
  "defaultM2": 110,
  "statutoryCapital": 50000,
  "isKosgebEligible": true,
  "kosgebCategory": "İleri Girişimci (Teknoloji/İmalat)",
  "competitorPoiCategory": "service",
  "primaryAuthority": "Madeni Eşya ve Sanatkarlar Odası & Sanayi İl Müdürlüğü"
},
];

/**
 * Türkçe alfabeye göre sıralanmış (A-Z) master sektör listesi döndürür.
 */
export function getSortedMasterSectors(): MasterSectorDefinition[] {
  return [...MASTER_SECTORS_LIST].sort((a, b) => a.name.localeCompare(b.name, 'tr'));
}

export function getMasterSectorById(sectorId: string): MasterSectorDefinition {
  const found = MASTER_SECTORS_LIST.find((s) => s.id === sectorId);
  return found || MASTER_SECTORS_LIST[MASTER_SECTORS_LIST.length - 1]; // fallback to software
}
