import type { QuickLocationPreset, RadarCategoryKey, RadarCategoryMeta } from '@/types/radar.types';

export const RADAR_CATEGORIES: Record<string, RadarCategoryMeta> = {
  // --- TOP 8 POPÜLER SEKTÖRLER ---
  cafe: {
    key: 'cafe',
    label: 'Kafe & Kahve Dükkanı',
    emoji: '☕',
    iconName: 'Coffee',
    accent: '#F59E0B',
    overpassFilter: '[amenity~cafe|coffee_shop|restaurant|fast_food|tea]',
    averageCatchmentRadius: 400,
    idealDensityPerKm2: 45,
    isPopularTop8: true,
    searchKeywords: ['kafe', 'kahve', 'cafe', 'coffee', 'çay', 'tatlıcı', 'espresso', 'üçüncü nesil'],
  },
  pet_shop: {
    key: 'pet_shop',
    label: 'Petshop & Veteriner',
    emoji: '🐾',
    iconName: 'Dog',
    accent: '#EC4899',
    overpassFilter: '[shop~pet|pet_grooming|veterinary]',
    averageCatchmentRadius: 750,
    idealDensityPerKm2: 8,
    isPopularTop8: true,
    searchKeywords: ['petshop', 'pet shop', 'veteriner', 'evcil hayvan', 'köpek', 'kedi', 'mama', 'kuaför'],
  },
  butcher: {
    key: 'butcher',
    label: 'Kasap & Şarküteri',
    emoji: '🥩',
    iconName: 'Flame',
    accent: '#DC2626',
    overpassFilter: '[shop~butcher|deli]',
    averageCatchmentRadius: 500,
    idealDensityPerKm2: 12,
    isPopularTop8: true,
    searchKeywords: ['kasap', 'şarküteri', 'et', 'tavuk', 'gurme', 'meze', 'peynir'],
  },
  bakery: {
    key: 'bakery',
    label: 'Fırın & Unlu Mamüller',
    emoji: '🥖',
    iconName: 'UtensilsCrossed',
    accent: '#D97706',
    overpassFilter: '[shop~bakery|pastry|confectionery]',
    averageCatchmentRadius: 400,
    idealDensityPerKm2: 20,
    isPopularTop8: true,
    searchKeywords: ['fırın', 'pastane', 'ekmek', 'unlu mamül', 'simit', 'börek', 'pasta', 'tatlı'],
  },
  market: {
    key: 'market',
    label: 'Market & Bakkal',
    emoji: '🛒',
    iconName: 'ShoppingBag',
    accent: '#06B6D4',
    overpassFilter: '[shop~supermarket|convenience|grocery]',
    averageCatchmentRadius: 300,
    idealDensityPerKm2: 30,
    isPopularTop8: true,
    searchKeywords: ['market', 'bakkal', 'süpermarket', 'tekel', 'şarküteri', 'manav', 'gıda'],
  },
  hairdresser: {
    key: 'hairdresser',
    label: 'Kuaför & Güzellik',
    emoji: '💈',
    iconName: 'Scissors',
    accent: '#8B5CF6',
    overpassFilter: '[shop~hairdresser|beauty|barber]',
    averageCatchmentRadius: 350,
    idealDensityPerKm2: 25,
    isPopularTop8: true,
    searchKeywords: ['kuaför', 'berber', 'güzellik', 'saç', 'tırnak', 'estetik', 'solaryum', 'barber'],
  },
  gym: {
    key: 'gym',
    label: 'Fitness & Spor Salonu',
    emoji: '🏋️',
    iconName: 'Dumbbell',
    accent: '#10B981',
    overpassFilter: '[leisure~fitness_centre|sports_centre|fitness_station]',
    averageCatchmentRadius: 900,
    idealDensityPerKm2: 5,
    isPopularTop8: true,
    searchKeywords: ['fitness', 'spor', 'gym', 'pilates', 'yoga', 'crossfit', 'vücut geliştirme', 'antrenman'],
  },
  pharmacy: {
    key: 'pharmacy',
    label: 'Eczane & Medikal',
    emoji: '💊',
    iconName: 'Cross',
    accent: '#14B8A6',
    overpassFilter: '[amenity=pharmacy]',
    averageCatchmentRadius: 500,
    idealDensityPerKm2: 12,
    isPopularTop8: true,
    searchKeywords: ['eczane', 'medikal', 'ilaç', 'sağlık', 'ortopedi', 'dermokozmetik'],
  },

  // --- TÜM GENİŞLETİLMİŞ VE ARAMADA ÇIKAN SEKTÖRLER ---
  insurance_agency: {
    key: 'insurance_agency',
    label: 'Sigorta Acentesi',
    emoji: '🛡️',
    iconName: 'ShieldCheck',
    accent: '#2563EB',
    overpassFilter: '[office~insurance|financial]',
    averageCatchmentRadius: 800,
    idealDensityPerKm2: 4,
    isPopularTop8: false,
    searchKeywords: ['acente', 'sigorta acentesi', 'kasko', 'trafik sigortası', 'dask', 'bireysel emeklilik', 'broker'],
  },
  travel_agency: {
    key: 'travel_agency',
    label: 'Turizm & Seyahat Acentesi',
    emoji: '✈️',
    iconName: 'Plane',
    accent: '#0284C7',
    overpassFilter: '[shop=travel_agency]',
    averageCatchmentRadius: 1000,
    idealDensityPerKm2: 3,
    isPopularTop8: false,
    searchKeywords: ['acente', 'turizm acentesi', 'seyahat', 'tur', 'bilet', 'vize', 'otel', 'tatil'],
  },
  real_estate: {
    key: 'real_estate',
    label: 'Emlak & Gayrimenkul Ofisi',
    emoji: '🏠',
    iconName: 'Building',
    accent: '#D97706',
    overpassFilter: '[office=estate_agent]',
    averageCatchmentRadius: 600,
    idealDensityPerKm2: 10,
    isPopularTop8: false,
    searchKeywords: ['emlak', 'gayrimenkul', 'remax', 'kiralık', 'satılık', 'konut', 'arsa', 'ofis'],
  },
  auto_gallery: {
    key: 'auto_gallery',
    label: 'Oto Galeri & Araç Kiralama',
    emoji: '🚘',
    iconName: 'Car',
    accent: '#475569',
    overpassFilter: '[shop~car|car_repair|car_parts]',
    averageCatchmentRadius: 1500,
    idealDensityPerKm2: 4,
    isPopularTop8: false,
    searchKeywords: ['oto galeri', 'araba', 'rent a car', 'araç kiralama', 'galeri', 'ikinci el'],
  },
  car_wash: {
    key: 'car_wash',
    label: 'Oto Yıkama & Detailing',
    emoji: '🚗',
    iconName: 'Car',
    accent: '#3B82F6',
    overpassFilter: '[amenity=car_wash]',
    averageCatchmentRadius: 1500,
    idealDensityPerKm2: 3,
    isPopularTop8: false,
    searchKeywords: ['oto yıkama', 'yıkama', 'detailing', 'pasta cila', 'seramik kaplama', 'lastik'],
  },
  restaurant: {
    key: 'restaurant',
    label: 'Restoran & Lokanta',
    emoji: '🍽️',
    iconName: 'Utensils',
    accent: '#EF4444',
    overpassFilter: '[amenity=restaurant]',
    averageCatchmentRadius: 500,
    idealDensityPerKm2: 35,
    isPopularTop8: false,
    searchKeywords: ['restoran', 'lokanta', 'kebap', 'döner', 'pizza', 'burger', 'balık', 'meyhane'],
  },
  boutique: {
    key: 'boutique',
    label: 'Butik & Giyim Mağazası',
    emoji: '👗',
    iconName: 'ShoppingBag',
    accent: '#A855F7',
    overpassFilter: '[shop~clothes|boutique|fashion]',
    averageCatchmentRadius: 600,
    idealDensityPerKm2: 15,
    isPopularTop8: false,
    searchKeywords: ['butik', 'giyim', 'tekstil', 'elbise', 'moda', 'tasarım', 'ayakkabı', 'çanta'],
  },
  stationery: {
    key: 'stationery',
    label: 'Kırtasiye & Kitabevi',
    emoji: '📚',
    iconName: 'BookOpen',
    accent: '#F97316',
    overpassFilter: '[shop~stationery|books]',
    averageCatchmentRadius: 600,
    idealDensityPerKm2: 8,
    isPopularTop8: false,
    searchKeywords: ['kırtasiye', 'kitap', 'fotokopi', 'okul', 'oyuncak', 'kitabevi', 'ofis malzemeleri'],
  },
  florist: {
    key: 'florist',
    label: 'Çiçekçi & Botanik',
    emoji: '💐',
    iconName: 'Flower2',
    accent: '#EC4899',
    overpassFilter: '[shop=florist]',
    averageCatchmentRadius: 700,
    idealDensityPerKm2: 5,
    isPopularTop8: false,
    searchKeywords: ['çiçekçi', 'çiçek', 'botanik', 'peyzaj', 'buket', 'orkide'],
  },
  optician: {
    key: 'optician',
    label: 'Optik & Gözlükçü',
    emoji: '👓',
    iconName: 'Glasses',
    accent: '#0EA5E9',
    overpassFilter: '[shop=optician]',
    averageCatchmentRadius: 800,
    idealDensityPerKm2: 6,
    isPopularTop8: false,
    searchKeywords: ['optik', 'gözlük', 'lens', 'gözlükçü', 'çerçeve'],
  },
  dry_cleaning: {
    key: 'dry_cleaning',
    label: 'Kuru Temizleme & Terzi',
    emoji: '👔',
    iconName: 'Sparkles',
    accent: '#64748B',
    overpassFilter: '[shop~dry_cleaning|laundry|tailor]',
    averageCatchmentRadius: 700,
    idealDensityPerKm2: 6,
    isPopularTop8: false,
    searchKeywords: ['kuru temizleme', 'terzi', 'ütü', 'laundry', 'tadilat', 'dikim'],
  },
  // --- DETAYLI MİKRO SEKTÖRLER (BÖREKÇİ, DONDURMACI, LASTİKÇİ VB.) ---
  borekci: {
    key: 'borekci',
    label: 'Börekçi & Poğaçacı',
    emoji: '🥟',
    iconName: 'UtensilsCrossed',
    accent: '#EA580C',
    overpassFilter: '[shop~bakery|pastry]',
    averageCatchmentRadius: 350,
    idealDensityPerKm2: 15,
    isPopularTop8: false,
    searchKeywords: ['börekçi', 'börek', 'kır pidesi', 'su böreği', 'kol böreği', 'poğaça', 'boyoz', 'açma', 'kahvaltı'],
  },
  dondurmaci: {
    key: 'dondurmaci',
    label: 'Dondurmacı & Waffle',
    emoji: '🍦',
    iconName: 'Sparkles',
    accent: '#EC4899',
    overpassFilter: '[amenity~ice_cream|cafe]',
    averageCatchmentRadius: 450,
    idealDensityPerKm2: 10,
    isPopularTop8: false,
    searchKeywords: ['dondurmacı', 'dondurma', 'gelato', 'waffle', 'maraş dondurması', 'tatlıcı', 'donuk yoğurt'],
  },
  lastikci: {
    key: 'lastikci',
    label: 'Oto Lastikçi & Rot Balans',
    emoji: '🛞',
    iconName: 'Car',
    accent: '#334155',
    overpassFilter: '[shop~tyres|car_repair]',
    averageCatchmentRadius: 1200,
    idealDensityPerKm2: 4,
    isPopularTop8: false,
    searchKeywords: ['lastikçi', 'lastik', 'oto lastik', 'rot balans', 'jant', 'lastik tamiri', 'akü', 'oto'],
  },
  cigkofteci: {
    key: 'cigkofteci',
    label: 'Çiğ Köfteci',
    emoji: '🌯',
    iconName: 'Flame',
    accent: '#B91C1C',
    overpassFilter: '[amenity~fast_food|restaurant]',
    averageCatchmentRadius: 300,
    idealDensityPerKm2: 25,
    isPopularTop8: false,
    searchKeywords: ['çiğ köfteci', 'çiğköfte', 'çiğ köfte', 'dürüm', 'komagene', 'battalbey', 'o ses'],
  },
  tatlici: {
    key: 'tatlici',
    label: 'Tatlıcı & Baklavacı',
    emoji: '🥮',
    iconName: 'Sparkles',
    accent: '#D97706',
    overpassFilter: '[shop~confectionery|pastry|bakery]',
    averageCatchmentRadius: 400,
    idealDensityPerKm2: 14,
    isPopularTop8: false,
    searchKeywords: ['tatlıcı', 'baklava', 'künefe', 'kadayıf', 'şerbetli tatlı', 'tulumba', 'profiterol', 'muhallebici'],
  },
  donerci: {
    key: 'donerci',
    label: 'Dönerci & Kebapçı',
    emoji: '🥙',
    iconName: 'Utensils',
    accent: '#DC2626',
    overpassFilter: '[amenity~restaurant|fast_food]',
    averageCatchmentRadius: 400,
    idealDensityPerKm2: 30,
    isPopularTop8: false,
    searchKeywords: ['dönerci', 'döner', 'et döner', 'tavuk döner', 'iskender', 'kebap', 'dürümcü', 'pide'],
  },
  kokorecci: {
    key: 'kokorecci',
    label: 'Kokoreççi & Sokak Lezzeti',
    emoji: '🍢',
    iconName: 'Flame',
    accent: '#9A3412',
    overpassFilter: '[amenity~fast_food|restaurant]',
    averageCatchmentRadius: 500,
    idealDensityPerKm2: 8,
    isPopularTop8: false,
    searchKeywords: ['kokoreççi', 'kokoreç', 'midye', 'midyeci', 'sokak lezzeti', 'köfte ekmek'],
  },
  cilingir: {
    key: 'cilingir',
    label: 'Çilingir & Anahtarcı',
    emoji: '🔑',
    iconName: 'Key',
    accent: '#EAB308',
    overpassFilter: '[shop=locksmith]',
    averageCatchmentRadius: 800,
    idealDensityPerKm2: 5,
    isPopularTop8: false,
    searchKeywords: ['çilingir', 'anahtarcı', 'kilit', 'kapı kilidi', 'oto anahtar', 'anahtar'],
  },
  balikci: {
    key: 'balikci',
    label: 'Balıkçı & Balık Pişiricisi',
    emoji: '🐟',
    iconName: 'Utensils',
    accent: '#0284C7',
    overpassFilter: '[shop=seafood]',
    averageCatchmentRadius: 800,
    idealDensityPerKm2: 4,
    isPopularTop8: false,
    searchKeywords: ['balıkçı', 'balık', 'taze balık', 'balık ekmek', 'hamsi', 'deniz ürünleri'],
  },
  manav: {
    key: 'manav',
    label: 'Manav & Organik Pazar',
    emoji: '🍎',
    iconName: 'ShoppingBag',
    accent: '#16A34A',
    overpassFilter: '[shop=greengrocer]',
    averageCatchmentRadius: 350,
    idealDensityPerKm2: 12,
    isPopularTop8: false,
    searchKeywords: ['manav', 'meyve', 'sebze', 'organik', 'yeşillik', 'köy ürünleri'],
  },
  terzi: {
    key: 'terzi',
    label: 'Terzi & Dikimevi',
    emoji: '🪡',
    iconName: 'Scissors',
    accent: '#7C3AED',
    overpassFilter: '[shop=tailor]',
    averageCatchmentRadius: 600,
    idealDensityPerKm2: 8,
    isPopularTop8: false,
    searchKeywords: ['terzi', 'dikim', 'tadilat', 'paça', 'elbise dikim', 'abiye', 'kumaş'],
  },
  oto_elektrik: {
    key: 'oto_elektrik',
    label: 'Oto Elektrik & Akücü',
    emoji: '⚡',
    iconName: 'Zap',
    accent: '#F59E0B',
    overpassFilter: '[shop~car_repair|car_parts]',
    averageCatchmentRadius: 1500,
    idealDensityPerKm2: 3,
    isPopularTop8: false,
    searchKeywords: ['oto elektrik', 'akü', 'akücü', 'marş motoru', 'oto klima', 'oto elektronik'],
  },
  dental_clinic: {
    key: 'dental_clinic',
    label: 'Diş Kliniği & Poliklinik',
    emoji: '🦷',
    iconName: 'Smile',
    accent: '#06B6D4',
    overpassFilter: '[amenity=dentist]',
    averageCatchmentRadius: 900,
    idealDensityPerKm2: 7,
    isPopularTop8: false,
    searchKeywords: ['diş', 'diş hekimi', 'klinik', 'poliklinik', 'ağız ve diş', 'implant'],
  },
  kindergarten: {
    key: 'kindergarten',
    label: 'Anaokulu & Kreş',
    emoji: '🧸',
    iconName: 'HeartHandshake',
    accent: '#F59E0B',
    overpassFilter: '[amenity=kindergarten]',
    averageCatchmentRadius: 1000,
    idealDensityPerKm2: 4,
    isPopularTop8: false,
    searchKeywords: ['anaokulu', 'kreş', 'çocuk kulübü', 'gündüz bakımevi', 'oyun evi', 'eğitim'],
  },
  law_firm: {
    key: 'law_firm',
    label: 'Hukuk & Avukatlık Ofisi',
    emoji: '⚖️',
    iconName: 'Scale',
    accent: '#334155',
    overpassFilter: '[office=lawyer]',
    averageCatchmentRadius: 800,
    idealDensityPerKm2: 12,
    isPopularTop8: false,
    searchKeywords: ['avukat', 'hukuk', 'danışmanlık', 'hukuk bürosu', 'arabuluculuk'],
  },
  software_agency: {
    key: 'software_agency',
    label: 'Yazılım & Bilişim Ofisi',
    emoji: '💻',
    iconName: 'Code',
    accent: '#6366F1',
    overpassFilter: '[office~it|software|company]',
    averageCatchmentRadius: 1200,
    idealDensityPerKm2: 15,
    isPopularTop8: false,
    searchKeywords: ['yazılım', 'bilişim', 'ajans', 'dijital pazarlama', 'yazılım ajansı', 'web tasarım'],
  },
  furniture: {
    key: 'furniture',
    label: 'Mobilya & Ev Dekorasyon',
    emoji: '🛋️',
    iconName: 'Armchair',
    accent: '#854D0E',
    overpassFilter: '[shop~furniture|interior_decoration]',
    averageCatchmentRadius: 1500,
    idealDensityPerKm2: 4,
    isPopularTop8: false,
    searchKeywords: ['mobilya', 'dekorasyon', 'koltuk', 'yatak', 'masa', 'ev eşyası'],
  },
  electronics: {
    key: 'electronics',
    label: 'Elektronik & Telefon Tamiri',
    emoji: '📱',
    iconName: 'Smartphone',
    accent: '#4F46E5',
    overpassFilter: '[shop~electronics|mobile_phone]',
    averageCatchmentRadius: 700,
    idealDensityPerKm2: 8,
    isPopularTop8: false,
    searchKeywords: ['telefon', 'elektronik', 'tamir', 'cep telefonu', 'bilgisayar tamiri', 'aksesuar'],
  },
  zuccaciye: {
    key: 'zuccaciye',
    label: 'Züccaciye & Ev Gereçleri',
    emoji: '🍽️',
    iconName: 'ShoppingBag',
    accent: '#0891B2',
    overpassFilter: '[shop~houseware|kitchen]',
    averageCatchmentRadius: 600,
    idealDensityPerKm2: 8,
    isPopularTop8: false,
    searchKeywords: ['züccaciye', 'ev gereçleri', 'mutfak', 'porselen', 'tencere', 'bardak', 'plastik'],
  },
  hardware: {
    key: 'hardware',
    label: 'Nalburiye & Hırdavat',
    emoji: '🔨',
    iconName: 'Hammer',
    accent: '#B45309',
    overpassFilter: '[shop~hardware|doityourself]',
    averageCatchmentRadius: 700,
    idealDensityPerKm2: 6,
    isPopularTop8: false,
    searchKeywords: ['nalburiye', 'hırdavat', 'yapı market', 'boya', 'vida', 'tesisat', 'tamirat'],
  },
  perde: {
    key: 'perde',
    label: 'Perde & Ev Tekstili',
    emoji: '🪟',
    iconName: 'Sparkles',
    accent: '#7E22CE',
    overpassFilter: '[shop~curtain|fabric]',
    averageCatchmentRadius: 800,
    idealDensityPerKm2: 5,
    isPopularTop8: false,
    searchKeywords: ['perde', 'mefruşat', 'tül', 'stor', 'fon perde', 'ev tekstili', 'döşeme'],
  },
  jewelry: {
    key: 'jewelry',
    label: 'Kuyumcu & Sarraf',
    emoji: '💍',
    iconName: 'Sparkles',
    accent: '#EAB308',
    overpassFilter: '[shop=jewelry]',
    averageCatchmentRadius: 1000,
    idealDensityPerKm2: 6,
    isPopularTop8: false,
    searchKeywords: ['kuyumcu', 'altın', 'sarraf', 'pırlanta', 'bilezik', 'çeyrek altın', 'takı'],
  },
  parfumeri: {
    key: 'parfumeri',
    label: 'Parfümeri & Kozmetik',
    emoji: '💄',
    iconName: 'Sparkles',
    accent: '#DB2777',
    overpassFilter: '[shop~chemist|cosmetics|perfumery]',
    averageCatchmentRadius: 700,
    idealDensityPerKm2: 6,
    isPopularTop8: false,
    searchKeywords: ['parfümeri', 'kozmetik', 'makyaj', 'cilt bakımı', 'parfüm', 'koku'],
  },
  shoe_store: {
    key: 'shoe_store',
    label: 'Ayakkabıcı & Çanta',
    emoji: '👠',
    iconName: 'ShoppingBag',
    accent: '#9333EA',
    overpassFilter: '[shop=shoes]',
    averageCatchmentRadius: 800,
    idealDensityPerKm2: 5,
    isPopularTop8: false,
    searchKeywords: ['ayakkabı', 'ayakkabıcı', 'çanta', 'deri', 'spor ayakkabı', 'terlik'],
  },
  su_bayisi: {
    key: 'su_bayisi',
    label: 'Su & Damacana Bayisi',
    emoji: '💧',
    iconName: 'Droplet',
    accent: '#0284C7',
    overpassFilter: '[shop~beverages|water]',
    averageCatchmentRadius: 600,
    idealDensityPerKm2: 6,
    isPopularTop8: false,
    searchKeywords: ['su bayisi', 'damacana', 'erikli', 'sırma', 'pınar su', 'kaynak suyu'],
  },
  tup_bayisi: {
    key: 'tup_bayisi',
    label: 'Tüp & Gaz Dağıtım',
    emoji: '🔥',
    iconName: 'Flame',
    accent: '#DC2626',
    overpassFilter: '[shop~gas|fuel]',
    averageCatchmentRadius: 1200,
    idealDensityPerKm2: 3,
    isPopularTop8: false,
    searchKeywords: ['tüp bayisi', 'tüp', 'aygaz', 'ipragaz', 'milangaz', 'mutfak tüpü'],
  },
  kuruyemis: {
    key: 'kuruyemis',
    label: 'Kuruyemiş & Kahve',
    emoji: '🥜',
    iconName: 'Coffee',
    accent: '#92400E',
    overpassFilter: '[shop~nuts|coffee|confectionery]',
    averageCatchmentRadius: 500,
    idealDensityPerKm2: 7,
    isPopularTop8: false,
    searchKeywords: ['kuruyemiş', 'kuruyemişçi', 'çerez', 'fındık', 'fıstık', 'kahve', 'şekerleme'],
  },
  hali_yikama: {
    key: 'hali_yikama',
    label: 'Halı Yıkama Servisi',
    emoji: '🧼',
    iconName: 'Sparkles',
    accent: '#0D9488',
    overpassFilter: '[shop~laundry|cleaning]',
    averageCatchmentRadius: 1500,
    idealDensityPerKm2: 3,
    isPopularTop8: false,
    searchKeywords: ['halı yıkama', 'koltuk yıkama', 'temizleme', 'perde yıkama'],
  },
  appliance_repair: {
    key: 'appliance_repair',
    label: 'Beyaz Eşya Servisi',
    emoji: '🔌',
    iconName: 'Wrench',
    accent: '#475569',
    overpassFilter: '[shop~appliance|electronics_repair]',
    averageCatchmentRadius: 1500,
    idealDensityPerKm2: 3,
    isPopularTop8: false,
    searchKeywords: ['beyaz eşya servisi', 'kombi servisi', 'klima servisi', 'çamaşır makinesi tamiri'],
  },
  photographer: {
    key: 'photographer',
    label: 'Fotoğrafçı & Stüdyo',
    emoji: '📸',
    iconName: 'Camera',
    accent: '#6366F1',
    overpassFilter: '[shop=photo]',
    averageCatchmentRadius: 900,
    idealDensityPerKm2: 4,
    isPopularTop8: false,
    searchKeywords: ['fotoğrafçı', 'vesikalık', 'biyometrik', 'stüdyo', 'düğün çekimi'],
  },
  printing: {
    key: 'printing',
    label: 'Matbaa & Baskı Merkezi',
    emoji: '🖨️',
    iconName: 'Printer',
    accent: '#4338CA',
    overpassFilter: '[shop~copyshop|print]',
    averageCatchmentRadius: 1200,
    idealDensityPerKm2: 3,
    isPopularTop8: false,
    searchKeywords: ['matbaa', 'baskı', 'etiket', 'kartvizit', 'broşür', 'promosyon'],
  },
  cleaning_products: {
    key: 'cleaning_products',
    label: 'Temizlik Ürünleri Satışı',
    emoji: '🧽',
    iconName: 'Sparkles',
    accent: '#059669',
    overpassFilter: '[shop~cleaning|chemist]',
    averageCatchmentRadius: 1000,
    idealDensityPerKm2: 3,
    isPopularTop8: false,
    searchKeywords: ['temizlik ürünleri', 'deterjan', 'kimyasal', 'toptan temizlik'],
  },
  toy_store: {
    key: 'toy_store',
    label: 'Oyuncakçı & Hediye',
    emoji: '🎯',
    iconName: 'Gift',
    accent: '#E11D48',
    overpassFilter: '[shop=toys]',
    averageCatchmentRadius: 900,
    idealDensityPerKm2: 3,
    isPopularTop8: false,
    searchKeywords: ['oyuncak', 'oyuncakçı', 'akülü araba', 'bebek', 'lego', 'hediyelik'],
  },
  bicycle_repair: {
    key: 'bicycle_repair',
    label: 'Bisiklet & Scooter Tamiri',
    emoji: '🚲',
    iconName: 'Bike',
    accent: '#15803D',
    overpassFilter: '[shop=bicycle]',
    averageCatchmentRadius: 1200,
    idealDensityPerKm2: 2,
    isPopularTop8: false,
    searchKeywords: ['bisiklet', 'scooter', 'bisiklet tamiri', 'scooter tamiri', 'lastik'],
  },
  aktar: {
    key: 'aktar',
    label: 'Aktar & Baharatçı',
    emoji: '🌿',
    iconName: 'Leaf',
    accent: '#15803D',
    overpassFilter: '[shop~herbalist|spices]',
    averageCatchmentRadius: 800,
    idealDensityPerKm2: 4,
    isPopularTop8: false,
    searchKeywords: ['aktar', 'baharat', 'şifalı bitkiler', 'bitki çayı', 'doğal yağlar', 'baharatçı'],
  },
  playstation_cafe: {
    key: 'playstation_cafe',
    label: 'Playstation & Konsol Salonu',
    emoji: '🎮',
    iconName: 'Gamepad2',
    accent: '#3B82F6',
    overpassFilter: '[leisure~video_arcade|amusement_arcade]',
    averageCatchmentRadius: 800,
    idealDensityPerKm2: 4,
    isPopularTop8: false,
    searchKeywords: ['playstation', 'ps5', 'ps4', 'konsol', 'oyun salonu', 'fifa', 'pes', 'playstation cafe', 'konsol oyun', 'atari'],
  },
  internet_cafe: {
    key: 'internet_cafe',
    label: 'İnternet Cafe & E-Spor',
    emoji: '🖥️',
    iconName: 'Monitor',
    accent: '#06B6D4',
    overpassFilter: '[amenity=internet_cafe]',
    averageCatchmentRadius: 900,
    idealDensityPerKm2: 3,
    isPopularTop8: false,
    searchKeywords: ['internet cafe', 'internet kafe', 'e-spor', 'gaming', 'oyun', 'lan gaming', 'siber cafe', 'bilgisayar salonu', 'gaming arena'],
  },
  parti_evi: {
    key: 'parti_evi',
    label: 'Parti Evi & Oyun / Etkinlik',
    emoji: '🎈',
    iconName: 'Sparkles',
    accent: '#F43F5E',
    overpassFilter: '[amenity~childcare|events_venue]',
    averageCatchmentRadius: 1000,
    idealDensityPerKm2: 3,
    isPopularTop8: false,
    searchKeywords: ['parti evi', 'doğum günü', 'etkinlik evi', 'çocuk atölyesi', 'organizasyon', 'baby shower', 'oyun evi', 'çocuk kulübü'],
  },
  oto_ekspertiz: {
    key: 'oto_ekspertiz',
    label: 'Oto Ekspertiz & Dyno Test',
    emoji: '🔍',
    iconName: 'Car',
    accent: '#F97316',
    overpassFilter: '[shop~car_repair|car_parts]',
    averageCatchmentRadius: 1500,
    idealDensityPerKm2: 3,
    isPopularTop8: false,
    searchKeywords: ['oto ekspertiz', 'ekspertiz', 'dyno', 'tse ekspertiz', 'computest', 'araç muayene', 'motor test', 'kaporta ekspertiz'],
  },
  pilates_studio: {
    key: 'pilates_studio',
    label: 'Reformer Pilates & Yoga',
    emoji: '🧘',
    iconName: 'Activity',
    accent: '#8B5CF6',
    overpassFilter: '[leisure~fitness_centre|dance]',
    averageCatchmentRadius: 750,
    idealDensityPerKm2: 5,
    isPopularTop8: false,
    searchKeywords: ['pilates', 'reformer', 'yoga', 'reformer pilates', 'aletli pilates', 'mat pilates', 'stüdyo', 'pilates stüdyosu'],
  },
  kitap_kafe: {
    key: 'kitap_kafe',
    label: 'Kitap Kafe & Çalışma Alanı',
    emoji: '📖',
    iconName: 'BookOpen',
    accent: '#D97706',
    overpassFilter: '[amenity~cafe|library]',
    averageCatchmentRadius: 800,
    idealDensityPerKm2: 4,
    isPopularTop8: false,
    searchKeywords: ['kitap kafe', 'kitap kahve', 'kütüphane', 'çalışma alanı', 'co-working', 'sessiz kafe', 'ders çalışma', 'okuma salonu'],
  },
  tattoo_studio: {
    key: 'tattoo_studio',
    label: 'Dövme & Piercing Stüdyosu',
    emoji: '✒️',
    iconName: 'Edit3',
    accent: '#64748B',
    overpassFilter: '[shop=tattoo]',
    averageCatchmentRadius: 1200,
    idealDensityPerKm2: 3,
    isPopularTop8: false,
    searchKeywords: ['dövme', 'tattoo', 'piercing', 'dövme stüdyosu', 'kalıcı makyaj', 'tattoo studio', 'dövmeci'],
  },
  dietitian: {
    key: 'dietitian',
    label: 'Diyetisyen & Beslenme Kliniği',
    emoji: '🥗',
    iconName: 'HeartPulse',
    accent: '#10B981',
    overpassFilter: '[healthcare~dietitian|nutritionist]',
    averageCatchmentRadius: 1000,
    idealDensityPerKm2: 3,
    isPopularTop8: false,
    searchKeywords: ['diyetisyen', 'beslenme', 'kilo verme', 'diyet', 'zayıflama', 'beslenme uzmanı', 'online diyet', 'andulasyon'],
  },
  kargo_subesi: {
    key: 'kargo_subesi',
    label: 'Kargo Şubesi & Dağıtım',
    emoji: '📦',
    iconName: 'Package',
    accent: '#EA580C',
    overpassFilter: '[amenity~post_office|parcel_locker]',
    averageCatchmentRadius: 700,
    idealDensityPerKm2: 5,
    isPopularTop8: false,
    searchKeywords: ['kargo', 'kargo şubesi', 'yurtiçi', 'aras', 'mng', 'sürat', 'ptt', 'trendyol express', 'hepsijet', 'paket'],
  },
  nail_art: {
    key: 'nail_art',
    label: 'Nail Art & Protez Tırnak Butiği',
    emoji: '💅',
    iconName: 'Sparkles',
    accent: '#F43F5E',
    overpassFilter: '[shop~beauty|nail_salon]',
    averageCatchmentRadius: 600,
    idealDensityPerKm2: 6,
    isPopularTop8: false,
    searchKeywords: ['nail art', 'tırnak', 'protez tırnak', 'kalıcı oje', 'manikür', 'pedikür', 'ipek kirpik', 'kirpik lifting'],
  },
  guzellik_merkezi: {
    key: 'guzellik_merkezi',
    label: 'Güzellik Merkezi & Lazer Epilasyon',
    emoji: '💆',
    iconName: 'Sparkles',
    accent: '#EC4899',
    overpassFilter: '[shop~beauty|massage]',
    averageCatchmentRadius: 800,
    idealDensityPerKm2: 5,
    isPopularTop8: false,
    searchKeywords: ['güzellik merkezi', 'lazer epilasyon', 'cilt bakımı', 'zayıflama', 'hydrafacial', 'bölgesel incelme', 'estetik'],
  },
  surucu_kursu: {
    key: 'surucu_kursu',
    label: 'Sürücü Kursu & Ehliyet',
    emoji: '🚗',
    iconName: 'Car',
    accent: '#0284C7',
    overpassFilter: '[amenity=driving_school]',
    averageCatchmentRadius: 1200,
    idealDensityPerKm2: 3,
    isPopularTop8: false,
    searchKeywords: ['sürücü kursu', 'ehliyet', 'direksiyon dersi', 'b sınıfı', 'a2 motor', 'özel direksiyon'],
  },
  dil_kursu: {
    key: 'dil_kursu',
    label: 'Yabancı Dil Kursu & Akademi',
    emoji: '🌐',
    iconName: 'Languages',
    accent: '#6366F1',
    overpassFilter: '[amenity~language_school|college]',
    averageCatchmentRadius: 1500,
    idealDensityPerKm2: 3,
    isPopularTop8: false,
    searchKeywords: ['dil kursu', 'ingilizce kursu', 'almanca', 'ielts', 'toefl', 'yabancı dil', 'hazırlık'],
  },
  etut_merkezi: {
    key: 'etut_merkezi',
    label: 'Etüt Merkezi, YKS & LGS Kursu',
    emoji: '🎓',
    iconName: 'GraduationCap',
    accent: '#4F46E5',
    overpassFilter: '[amenity~school|prep_school]',
    averageCatchmentRadius: 1000,
    idealDensityPerKm2: 4,
    isPopularTop8: false,
    searchKeywords: ['etüt merkezi', 'kurs', 'dershane', 'yks', 'lgs', 'kpss', 'özel ders', 'matematik kursu'],
  },
  corbaci: {
    key: 'corbaci',
    label: 'Çorbacı & Gece Lezzetleri',
    emoji: '🥣',
    iconName: 'Soup',
    accent: '#DC2626',
    overpassFilter: '[amenity~restaurant|fast_food]',
    averageCatchmentRadius: 750,
    idealDensityPerKm2: 4,
    isPopularTop8: false,
    searchKeywords: ['çorbacı', 'çorba', 'kelle paça', 'işkembe', 'mercimek', 'gece çorbacısı', 'beyran'],
  },
  bufe_tost: {
    key: 'bufe_tost',
    label: 'Büfe, Tost & Sandviç / Kumru',
    emoji: '🥪',
    iconName: 'Utensils',
    accent: '#D97706',
    overpassFilter: '[amenity~fast_food|kiosk]',
    averageCatchmentRadius: 500,
    idealDensityPerKm2: 8,
    isPopularTop8: false,
    searchKeywords: ['büfe', 'tost', 'sandviç', 'kumru', 'ayvalık tostu', 'sosisli', 'ıslak hamburger', 'marmaris büfe'],
  },
  kahvalti_salonu: {
    key: 'kahvalti_salonu',
    label: 'Kahvaltı Salonu & Serpme Kahvaltı',
    emoji: '🍳',
    iconName: 'UtensilsCrossed',
    accent: '#EAB308',
    overpassFilter: '[amenity~restaurant|cafe]',
    averageCatchmentRadius: 800,
    idealDensityPerKm2: 4,
    isPopularTop8: false,
    searchKeywords: ['kahvaltı', 'serpme kahvaltı', 'van kahvaltı', 'köy kahvaltısı', 'menemen', 'kahvaltı salonu'],
  },
  bubble_tea: {
    key: 'bubble_tea',
    label: 'Bubble Tea, Smoothie & Meyve Suyu',
    emoji: '🧋',
    iconName: 'Coffee',
    accent: '#06B6D4',
    overpassFilter: '[amenity~cafe|fast_food]',
    averageCatchmentRadius: 700,
    idealDensityPerKm2: 4,
    isPopularTop8: false,
    searchKeywords: ['bubble tea', 'boba tea', 'smoothie', 'meyve suyu', 'atom', 'taze sıkma portakal', 'milk tea'],
  },
  psikolog: {
    key: 'psikolog',
    label: 'Psikolog & Aile Danışmanlık',
    emoji: '🧠',
    iconName: 'HeartPulse',
    accent: '#14B8A6',
    overpassFilter: '[healthcare~psychotherapist|counselling]',
    averageCatchmentRadius: 1000,
    idealDensityPerKm2: 3,
    isPopularTop8: false,
    searchKeywords: ['psikolog', 'terapi', 'aile danışmanı', 'klinik psikolog', 'çocuk psikoloğu', 'emdr', 'bilişsel terapi'],
  },
  noter: {
    key: 'noter',
    label: 'Noter & Resmi Onay Dairesi',
    emoji: '📜',
    iconName: 'FileText',
    accent: '#475569',
    overpassFilter: '[amenity=notary]',
    averageCatchmentRadius: 1500,
    idealDensityPerKm2: 2,
    isPopularTop8: false,
    searchKeywords: ['noter', 'noterlik', 'vekaletname', 'araç satışı', 'tasdik', 'imza beyannamesi'],
  },
  mali_musavir: {
    key: 'mali_musavir',
    label: 'Mali Müşavir & Muhasebe Bürosu',
    emoji: '💼',
    iconName: 'Briefcase',
    accent: '#334155',
    overpassFilter: '[office~accountant|financial]',
    averageCatchmentRadius: 900,
    idealDensityPerKm2: 5,
    isPopularTop8: false,
    searchKeywords: ['mali müşavir', 'muhasebe', 'smmm', 'vergi', 'şirket kuruluşu', 'muhasebeci', 'e-fatura'],
  },
  motosiklet_servis: {
    key: 'motosiklet_servis',
    label: 'Motosiklet Servisi & Ekipman',
    emoji: '🏍️',
    iconName: 'Bike',
    accent: '#DC2626',
    overpassFilter: '[shop~motorcycle|motorcycle_repair]',
    averageCatchmentRadius: 1500,
    idealDensityPerKm2: 3,
    isPopularTop8: false,
    searchKeywords: ['motosiklet', 'motor servisi', 'kask', 'kurye ekipmanları', 'scooter motor', 'motor tamiri', 'zincir'],
  },
  oto_tuning: {
    key: 'oto_tuning',
    label: 'Oto Cam Filmi, PPF & Ses Sistemleri',
    emoji: '🎛️',
    iconName: 'Wrench',
    accent: '#8B5CF6',
    overpassFilter: '[shop~car_repair|car_parts]',
    averageCatchmentRadius: 1500,
    idealDensityPerKm2: 3,
    isPopularTop8: false,
    searchKeywords: ['cam filmi', 'ppf kaplama', 'oto ses sistemi', 'multimedya', 'araç kaplama', 'oto müzik'],
  },
  outdoor_kamp: {
    key: 'outdoor_kamp',
    label: 'Kamp, Balıkçılık & Outdoor',
    emoji: '🏕️',
    iconName: 'Compass',
    accent: '#15803D',
    overpassFilter: '[shop~outdoor|fishing|hunting]',
    averageCatchmentRadius: 1500,
    idealDensityPerKm2: 2,
    isPopularTop8: false,
    searchKeywords: ['kamp', 'çadır', 'outdoor', 'balık avı', 'olta', 'avcılık', 'termos', 'kamp sandalyesi'],
  },
  muzik_kursu: {
    key: 'muzik_kursu',
    label: 'Müzik Kursu & Enstrüman Satışı',
    emoji: '🎸',
    iconName: 'Music',
    accent: '#D97706',
    overpassFilter: '[shop~musical_instrument|music_school]',
    averageCatchmentRadius: 1200,
    idealDensityPerKm2: 3,
    isPopularTop8: false,
    searchKeywords: ['müzik kursu', 'gitar', 'piyano', 'keman', 'bateri', 'şandersi', 'müzik aletleri'],
  },
  antika_vintage: {
    key: 'antika_vintage',
    label: 'Antika, Vintage & Plak Dükkanı',
    emoji: '🏺',
    iconName: 'Sparkles',
    accent: '#78350F',
    overpassFilter: '[shop~antiques|second_hand|vintage]',
    averageCatchmentRadius: 1500,
    idealDensityPerKm2: 2,
    isPopularTop8: false,
    searchKeywords: ['antika', 'vintage', 'plak', 'retro', 'ikinci el', 'efemera', 'mezat', 'antikacı'],
  },
  tobacco_shop: {
    key: 'tobacco_shop',
    label: 'Tobacco Shop & Nargile / Puro',
    emoji: '🚬',
    iconName: 'Flame',
    accent: '#713F12',
    overpassFilter: '[shop=tobacco]',
    averageCatchmentRadius: 700,
    idealDensityPerKm2: 5,
    isPopularTop8: false,
    searchKeywords: ['tobacco shop', 'tütüncü', 'puro', 'nargile tütünü', 'kömür', 'pipo', 'tabaka'],
  },
  mimarlik_ofisi: {
    key: 'mimarlik_ofisi',
    label: 'Mimarlık & İç Mimarlık Tasarım',
    emoji: '🏛️',
    iconName: 'Building',
    accent: '#0F766E',
    overpassFilter: '[office~architect|interior_decorator]',
    averageCatchmentRadius: 1200,
    idealDensityPerKm2: 3,
    isPopularTop8: false,
    searchKeywords: ['mimarlık', 'iç mimarlık', 'dekorasyon', 'villa tasarımı', '3d modelleme', 'tadilat projesi'],
  },
  medikal_ortopedi: {
    key: 'medikal_ortopedi',
    label: 'Medikal & Ortopedi / Hasta Bakım',
    emoji: '🏥',
    iconName: 'Cross',
    accent: '#0D9488',
    overpassFilter: '[shop~medical_supply|chemist]',
    averageCatchmentRadius: 1000,
    idealDensityPerKm2: 3,
    isPopularTop8: false,
    searchKeywords: ['medikal', 'ortopedi', 'hasta yatağı', 'tekerlekli sandalye', 'korse', 'oksijen tüpü', 'tansiyon aleti'],
  },
  isitme_cihazi: {
    key: 'isitme_cihazi',
    label: 'İşitme Cihazları Satış Merkezi',
    emoji: '👂',
    iconName: 'Volume2',
    accent: '#2563EB',
    overpassFilter: '[shop~hearing_aids|chemist]',
    averageCatchmentRadius: 1500,
    idealDensityPerKm2: 2,
    isPopularTop8: false,
    searchKeywords: ['işitme cihazı', 'odyoloji', 'kulaklık', 'duyma testi', 'işitme merkezi'],
  },
  pub_meyhane: {
    key: 'pub_meyhane',
    label: 'Pub, Meyhane & Bira Evi / Gastro',
    emoji: '🍺',
    iconName: 'Beer',
    accent: '#B45309',
    overpassFilter: '[amenity~pub|bar]',
    averageCatchmentRadius: 800,
    idealDensityPerKm2: 4,
    isPopularTop8: false,
    searchKeywords: ['pub', 'meyhane', 'bira evi', 'gastropub', 'canlı müzik', 'yeni nesil meyhane', 'craft bira', 'meze'],
  },
  waffle_cikolata: {
    key: 'waffle_cikolata',
    label: 'Waffle & Butik Çikolata Atölyesi',
    emoji: '🍫',
    iconName: 'Cookie',
    accent: '#78350F',
    overpassFilter: '[shop~confectionery|pastry]',
    averageCatchmentRadius: 700,
    idealDensityPerKm2: 4,
    isPopularTop8: false,
    searchKeywords: ['waffle', 'çikolata', 'el yapımı çikolata', 'krep', 'fondü', 'belçika çikolatası', 'tatlı'],
  },
};

export const QUICK_LOCATION_PRESETS: QuickLocationPreset[] = [
  {
    id: 'ist-kadikoy-moda',
    name: 'Kadıköy / Moda',
    city: 'İstanbul',
    district: 'Kadıköy',
    lat: 40.9875,
    lng: 29.0289,
    zoom: 15,
    description: 'Yoğun yaya trafiği, genç & yaratıcı kitle',
  },
  {
    id: 'ist-besiktas-carsi',
    name: 'Beşiktaş / Çarşı',
    city: 'İstanbul',
    district: 'Beşiktaş',
    lat: 41.0428,
    lng: 29.0069,
    zoom: 15,
    description: 'Üniversite ve iş merkezi kesişimi',
  },
  {
    id: 'ist-sisli-nisantasi',
    name: 'Şişli / Nişantaşı',
    city: 'İstanbul',
    district: 'Şişli',
    lat: 41.0531,
    lng: 28.9928,
    zoom: 15,
    description: 'Yüksek alım gücü ve butik konseptler',
  },
  {
    id: 'ank-cankaya-tunali',
    name: 'Çankaya / Tunalı Hilmi',
    city: 'Ankara',
    district: 'Çankaya',
    lat: 39.9022,
    lng: 32.8601,
    zoom: 15,
    description: 'Bürokrasi, elçilikler ve sosyal yaşam merkezi',
  },
  {
    id: 'izm-karsiyaka-carsi',
    name: 'Karşıyaka / Çarşı',
    city: 'İzmir',
    district: 'Karşıyaka',
    lat: 38.4593,
    lng: 27.1124,
    zoom: 15,
    description: 'Kıyı şeridi ve yoğun yerel ticaret',
  },
  {
    id: 'ant-muratpasa-lara',
    name: 'Muratpaşa / Lara',
    city: 'Antalya',
    district: 'Muratpaşa',
    lat: 36.8584,
    lng: 30.7588,
    zoom: 14,
    description: 'Turizm, yabancı nüfus ve premium hizmetler',
  },
  {
    id: 'bur-nilufer-ozluce',
    name: 'Nilüfer / Özlüce',
    city: 'Bursa',
    district: 'Nilüfer',
    lat: 40.2198,
    lng: 28.9189,
    zoom: 14,
    description: 'Yeni nesil gastronomi ve modern konut bölgesi',
  },
];

export const RADAR_DEFAULT_CENTER = {
  lat: 40.9875,
  lng: 29.0289,
  zoom: 15,
};

export const RADAR_DEFAULT_RADIUS_METERS = 500;
