import type { QuickLocationPreset, RadarCategoryKey, RadarCategoryMeta } from '@/types/radar.types';

export const RADAR_CATEGORIES: Record<RadarCategoryKey, RadarCategoryMeta> = {
  cafe: {
    key: 'cafe',
    label: 'Kafe & Kahve Dükkanı',
    emoji: '☕',
    iconName: 'Coffee',
    accent: '#F59E0B',
    overpassFilter: '[amenity~cafe|coffee_shop|restaurant|fast_food]',
    averageCatchmentRadius: 400,
    idealDensityPerKm2: 45,
  },
  pet_shop: {
    key: 'pet_shop',
    label: 'Petshop & Veteriner',
    emoji: '🐾',
    iconName: 'Dog',
    accent: '#EC4899',
    overpassFilter: '[shop~pet|pet_grooming|veterinary]',
    averageCatchmentRadius: 750,
    idealDensityPerKm2: 8,
  },
  butcher: {
    key: 'butcher',
    label: 'Kasap & Şarküteri',
    emoji: '🥩',
    iconName: 'Flame',
    accent: '#DC2626',
    overpassFilter: '[shop~butcher|deli]',
    averageCatchmentRadius: 500,
    idealDensityPerKm2: 12,
  },
  bakery: {
    key: 'bakery',
    label: 'Fırın & Unlu Mamüller',
    emoji: '🥖',
    iconName: 'UtensilsCrossed',
    accent: '#D97706',
    overpassFilter: '[shop~bakery|pastry|confectionery]',
    averageCatchmentRadius: 400,
    idealDensityPerKm2: 20,
  },
  market: {
    key: 'market',
    label: 'Market & Bakkal',
    emoji: '🛒',
    iconName: 'ShoppingBag',
    accent: '#06B6D4',
    overpassFilter: '[shop~supermarket|convenience|grocery]',
    averageCatchmentRadius: 300,
    idealDensityPerKm2: 30,
  },
  hairdresser: {
    key: 'hairdresser',
    label: 'Kuaför & Güzellik',
    emoji: '💈',
    iconName: 'Scissors',
    accent: '#8B5CF6',
    overpassFilter: '[shop~hairdresser|beauty|barber]',
    averageCatchmentRadius: 350,
    idealDensityPerKm2: 25,
  },
  gym: {
    key: 'gym',
    label: 'Fitness & Spor Salonu',
    emoji: '🏋️',
    iconName: 'Dumbbell',
    accent: '#10B981',
    overpassFilter: '[leisure~fitness_centre|sports_centre|fitness_station]',
    averageCatchmentRadius: 900,
    idealDensityPerKm2: 5,
  },
  pharmacy: {
    key: 'pharmacy',
    label: 'Eczane & Medikal',
    emoji: '💊',
    iconName: 'Cross',
    accent: '#14B8A6',
    overpassFilter: '[amenity=pharmacy]',
    averageCatchmentRadius: 500,
    idealDensityPerKm2: 12,
  },
  car_wash: {
    key: 'car_wash',
    label: 'Oto Yıkama & Servis',
    emoji: '🚗',
    iconName: 'Car',
    accent: '#3B82F6',
    overpassFilter: '[amenity=car_wash]',
    averageCatchmentRadius: 1500,
    idealDensityPerKm2: 3,
  },
  restaurant: {
    key: 'restaurant',
    label: 'Restoran & Lokanta',
    emoji: '🍽️',
    iconName: 'Utensils',
    accent: '#EF4444',
    overpassFilter: '[amenity=restaurant]',
    averageCatchmentRadius: 500,
    idealDensityPerKm2: 35,
  },
  boutique: {
    key: 'boutique',
    label: 'Butik & Giyim Mağazası',
    emoji: '👗',
    iconName: 'ShoppingBag',
    accent: '#A855F7',
    overpassFilter: '[shop~clothes|boutique|fashion]',
    averageCatchmentRadius: 600,
    idealDensityPerKm2: 15,
  },
  dry_cleaning: {
    key: 'dry_cleaning',
    label: 'Kuru Temizleme & Terzi',
    emoji: '👔',
    iconName: 'Sparkles',
    accent: '#64748B',
    overpassFilter: '[shop~dry_cleaning|laundry|tailor]',
    averageCatchmentRadius: 700,
    idealDensityPerKm2: 6,
  },
};

export const QUICK_LOCATION_PRESETS: QuickLocationPreset[] = [
  {
    id: 'ist-kadikoy-moda',
    name: 'Kadıköy / Moda',
    city: 'İstanbul',
    district: 'Kadıköy',
    lat: 40.9875,
    lng: 29.0289,
    zoom: 15,
    description: 'Yoğun yaya trafiği, genç & yaratıcı kitle',
  },
  {
    id: 'ist-besiktas-carsi',
    name: 'Beşiktaş / Çarşı',
    city: 'İstanbul',
    district: 'Beşiktaş',
    lat: 41.0428,
    lng: 29.0069,
    zoom: 15,
    description: 'Üniversite ve iş merkezi kesişimi',
  },
  {
    id: 'ist-sisli-nisantasi',
    name: 'Şişli / Nişantaşı',
    city: 'İstanbul',
    district: 'Şişli',
    lat: 41.0531,
    lng: 28.9928,
    zoom: 15,
    description: 'Yüksek alım gücü ve butik konseptler',
  },
  {
    id: 'ank-cankaya-tunali',
    name: 'Çankaya / Tunalı Hilmi',
    city: 'Ankara',
    district: 'Çankaya',
    lat: 39.9022,
    lng: 32.8601,
    zoom: 15,
    description: 'Bürokrasi, elçilikler ve sosyal yaşam merkezi',
  },
  {
    id: 'izm-karsiyaka-carsi',
    name: 'Karşıyaka / Çarşı',
    city: 'İzmir',
    district: 'Karşıyaka',
    lat: 38.4593,
    lng: 27.1124,
    zoom: 15,
    description: 'Kıyı şeridi ve yoğun yerel ticaret',
  },
  {
    id: 'ant-muratpasa-lara',
    name: 'Muratpaşa / Lara',
    city: 'Antalya',
    district: 'Muratpaşa',
    lat: 36.8584,
    lng: 30.7588,
    zoom: 14,
    description: 'Turizm, yabancı nüfus ve premium hizmetler',
  },
  {
    id: 'bur-nilufer-ozluce',
    name: 'Nilüfer / Özlüce',
    city: 'Bursa',
    district: 'Nilüfer',
    lat: 40.2198,
    lng: 28.9189,
    zoom: 14,
    description: 'Yeni nesil gastronomi ve modern konut bölgesi',
  },
];

export const RADAR_DEFAULT_CENTER = {
  lat: 40.9875,
  lng: 29.0289,
  zoom: 15,
};

export const RADAR_DEFAULT_RADIUS_METERS = 500;
