import type { QuickLocationPreset, RadarCategoryKey, RadarCategoryMeta } from '@/types/radar.types';

export const RADAR_CATEGORIES: Record<string, RadarCategoryMeta> = {
  // --- TOP 8 POPÜLER SEKTÖRLER ---
  cafe: {
    key: 'cafe',
    label: 'Kafe & Kahve Dükkanı',
    emoji: '☕',
    iconName: 'Coffee',
    accent: '#F59E0B',
    overpassFilter: '[amenity~cafe|coffee_shop|restaurant|fast_food|tea]',
    averageCatchmentRadius: 400,
    idealDensityPerKm2: 45,
    isPopularTop8: true,
    searchKeywords: ['kafe', 'kahve', 'cafe', 'coffee', 'çay', 'tatlıcı', 'espresso', 'üçüncü nesil'],
  },
  pet_shop: {
    key: 'pet_shop',
    label: 'Petshop & Veteriner',
    emoji: '🐾',
    iconName: 'Dog',
    accent: '#EC4899',
    overpassFilter: '[shop~pet|pet_grooming|veterinary]',
    averageCatchmentRadius: 750,
    idealDensityPerKm2: 8,
    isPopularTop8: true,
    searchKeywords: ['petshop', 'pet shop', 'veteriner', 'evcil hayvan', 'köpek', 'kedi', 'mama', 'kuaför'],
  },
  butcher: {
    key: 'butcher',
    label: 'Kasap & Şarküteri',
    emoji: '🥩',
    iconName: 'Flame',
    accent: '#DC2626',
    overpassFilter: '[shop~butcher|deli]',
    averageCatchmentRadius: 500,
    idealDensityPerKm2: 12,
    isPopularTop8: true,
    searchKeywords: ['kasap', 'şarküteri', 'et', 'tavuk', 'gurme', 'meze', 'peynir'],
  },
  bakery: {
    key: 'bakery',
    label: 'Fırın & Unlu Mamüller',
    emoji: '🥖',
    iconName: 'UtensilsCrossed',
    accent: '#D97706',
    overpassFilter: '[shop~bakery|pastry|confectionery]',
    averageCatchmentRadius: 400,
    idealDensityPerKm2: 20,
    isPopularTop8: true,
    searchKeywords: ['fırın', 'pastane', 'ekmek', 'unlu mamül', 'simit', 'börek', 'pasta', 'tatlı'],
  },
  market: {
    key: 'market',
    label: 'Market & Bakkal',
    emoji: '🛒',
    iconName: 'ShoppingBag',
    accent: '#06B6D4',
    overpassFilter: '[shop~supermarket|convenience|grocery]',
    averageCatchmentRadius: 300,
    idealDensityPerKm2: 30,
    isPopularTop8: true,
    searchKeywords: ['market', 'bakkal', 'süpermarket', 'tekel', 'şarküteri', 'manav', 'gıda'],
  },
  hairdresser: {
    key: 'hairdresser',
    label: 'Kuaför & Güzellik',
    emoji: '💈',
    iconName: 'Scissors',
    accent: '#8B5CF6',
    overpassFilter: '[shop~hairdresser|beauty|barber]',
    averageCatchmentRadius: 350,
    idealDensityPerKm2: 25,
    isPopularTop8: true,
    searchKeywords: ['kuaför', 'berber', 'güzellik', 'saç', 'tırnak', 'estetik', 'solaryum', 'barber'],
  },
  gym: {
    key: 'gym',
    label: 'Fitness & Spor Salonu',
    emoji: '🏋️',
    iconName: 'Dumbbell',
    accent: '#10B981',
    overpassFilter: '[leisure~fitness_centre|sports_centre|fitness_station]',
    averageCatchmentRadius: 900,
    idealDensityPerKm2: 5,
    isPopularTop8: true,
    searchKeywords: ['fitness', 'spor', 'gym', 'pilates', 'yoga', 'crossfit', 'vücut geliştirme', 'antrenman'],
  },
  pharmacy: {
    key: 'pharmacy',
    label: 'Eczane & Medikal',
    emoji: '💊',
    iconName: 'Cross',
    accent: '#14B8A6',
    overpassFilter: '[amenity=pharmacy]',
    averageCatchmentRadius: 500,
    idealDensityPerKm2: 12,
    isPopularTop8: true,
    searchKeywords: ['eczane', 'medikal', 'ilaç', 'sağlık', 'ortopedi', 'dermokozmetik'],
  },

  // --- TÜM GENİŞLETİLMİŞ VE ARAMADA ÇIKAN SEKTÖRLER ---
  insurance_agency: {
    key: 'insurance_agency',
    label: 'Sigorta Acentesi',
    emoji: '🛡️',
    iconName: 'ShieldCheck',
    accent: '#2563EB',
    overpassFilter: '[office~insurance|financial]',
    averageCatchmentRadius: 800,
    idealDensityPerKm2: 4,
    isPopularTop8: false,
    searchKeywords: ['acente', 'sigorta acentesi', 'kasko', 'trafik sigortası', 'dask', 'bireysel emeklilik', 'broker'],
  },
  travel_agency: {
    key: 'travel_agency',
    label: 'Turizm & Seyahat Acentesi',
    emoji: '✈️',
    iconName: 'Plane',
    accent: '#0284C7',
    overpassFilter: '[shop=travel_agency]',
    averageCatchmentRadius: 1000,
    idealDensityPerKm2: 3,
    isPopularTop8: false,
    searchKeywords: ['acente', 'turizm acentesi', 'seyahat', 'tur', 'bilet', 'vize', 'otel', 'tatil'],
  },
  real_estate: {
    key: 'real_estate',
    label: 'Emlak & Gayrimenkul Ofisi',
    emoji: '🏠',
    iconName: 'Building',
    accent: '#D97706',
    overpassFilter: '[office=estate_agent]',
    averageCatchmentRadius: 600,
    idealDensityPerKm2: 10,
    isPopularTop8: false,
    searchKeywords: ['emlak', 'gayrimenkul', 'remax', 'kiralık', 'satılık', 'konut', 'arsa', 'ofis'],
  },
  auto_gallery: {
    key: 'auto_gallery',
    label: 'Oto Galeri & Araç Kiralama',
    emoji: '🚘',
    iconName: 'Car',
    accent: '#475569',
    overpassFilter: '[shop~car|car_repair|car_parts]',
    averageCatchmentRadius: 1500,
    idealDensityPerKm2: 4,
    isPopularTop8: false,
    searchKeywords: ['oto galeri', 'araba', 'rent a car', 'araç kiralama', 'galeri', 'ikinci el'],
  },
  car_wash: {
    key: 'car_wash',
    label: 'Oto Yıkama & Detailing',
    emoji: '🚗',
    iconName: 'Car',
    accent: '#3B82F6',
    overpassFilter: '[amenity=car_wash]',
    averageCatchmentRadius: 1500,
    idealDensityPerKm2: 3,
    isPopularTop8: false,
    searchKeywords: ['oto yıkama', 'yıkama', 'detailing', 'pasta cila', 'seramik kaplama', 'lastik'],
  },
  restaurant: {
    key: 'restaurant',
    label: 'Restoran & Lokanta',
    emoji: '🍽️',
    iconName: 'Utensils',
    accent: '#EF4444',
    overpassFilter: '[amenity=restaurant]',
    averageCatchmentRadius: 500,
    idealDensityPerKm2: 35,
    isPopularTop8: false,
    searchKeywords: ['restoran', 'lokanta', 'kebap', 'döner', 'pizza', 'burger', 'balık', 'meyhane'],
  },
  boutique: {
    key: 'boutique',
    label: 'Butik & Giyim Mağazası',
    emoji: '👗',
    iconName: 'ShoppingBag',
    accent: '#A855F7',
    overpassFilter: '[shop~clothes|boutique|fashion]',
    averageCatchmentRadius: 600,
    idealDensityPerKm2: 15,
    isPopularTop8: false,
    searchKeywords: ['butik', 'giyim', 'tekstil', 'elbise', 'moda', 'tasarım', 'ayakkabı', 'çanta'],
  },
  stationery: {
    key: 'stationery',
    label: 'Kırtasiye & Kitabevi',
    emoji: '📚',
    iconName: 'BookOpen',
    accent: '#F97316',
    overpassFilter: '[shop~stationery|books]',
    averageCatchmentRadius: 600,
    idealDensityPerKm2: 8,
    isPopularTop8: false,
    searchKeywords: ['kırtasiye', 'kitap', 'fotokopi', 'okul', 'oyuncak', 'kitabevi', 'ofis malzemeleri'],
  },
  florist: {
    key: 'florist',
    label: 'Çiçekçi & Botanik',
    emoji: '💐',
    iconName: 'Flower2',
    accent: '#EC4899',
    overpassFilter: '[shop=florist]',
    averageCatchmentRadius: 700,
    idealDensityPerKm2: 5,
    isPopularTop8: false,
    searchKeywords: ['çiçekçi', 'çiçek', 'botanik', 'peyzaj', 'buket', 'orkide'],
  },
  optician: {
    key: 'optician',
    label: 'Optik & Gözlükçü',
    emoji: '👓',
    iconName: 'Glasses',
    accent: '#0EA5E9',
    overpassFilter: '[shop=optician]',
    averageCatchmentRadius: 800,
    idealDensityPerKm2: 6,
    isPopularTop8: false,
    searchKeywords: ['optik', 'gözlük', 'lens', 'gözlükçü', 'çerçeve'],
  },
  dry_cleaning: {
    key: 'dry_cleaning',
    label: 'Kuru Temizleme & Terzi',
    emoji: '👔',
    iconName: 'Sparkles',
    accent: '#64748B',
    overpassFilter: '[shop~dry_cleaning|laundry|tailor]',
    averageCatchmentRadius: 700,
    idealDensityPerKm2: 6,
    isPopularTop8: false,
    searchKeywords: ['kuru temizleme', 'terzi', 'ütü', 'laundry', 'tadilat', 'dikim'],
  },
  dental_clinic: {
    key: 'dental_clinic',
    label: 'Diş Kliniği & Poliklinik',
    emoji: '🦷',
    iconName: 'Smile',
    accent: '#06B6D4',
    overpassFilter: '[amenity=dentist]',
    averageCatchmentRadius: 900,
    idealDensityPerKm2: 7,
    isPopularTop8: false,
    searchKeywords: ['diş', 'diş hekimi', 'klinik', 'poliklinik', 'ağız ve diş', 'implant'],
  },
  kindergarten: {
    key: 'kindergarten',
    label: 'Anaokulu & Kreş',
    emoji: '🧸',
    iconName: 'HeartHandshake',
    accent: '#F59E0B',
    overpassFilter: '[amenity=kindergarten]',
    averageCatchmentRadius: 1000,
    idealDensityPerKm2: 4,
    isPopularTop8: false,
    searchKeywords: ['anaokulu', 'kreş', 'çocuk kulübü', 'gündüz bakımevi', 'oyun evi', 'eğitim'],
  },
  law_firm: {
    key: 'law_firm',
    label: 'Hukuk & Avukatlık Ofisi',
    emoji: '⚖️',
    iconName: 'Scale',
    accent: '#334155',
    overpassFilter: '[office=lawyer]',
    averageCatchmentRadius: 800,
    idealDensityPerKm2: 12,
    isPopularTop8: false,
    searchKeywords: ['avukat', 'hukuk', 'danışmanlık', 'hukuk bürosu', 'arabuluculuk'],
  },
  software_agency: {
    key: 'software_agency',
    label: 'Yazılım & Bilişim Ofisi',
    emoji: '💻',
    iconName: 'Code',
    accent: '#6366F1',
    overpassFilter: '[office~it|software|company]',
    averageCatchmentRadius: 1200,
    idealDensityPerKm2: 15,
    isPopularTop8: false,
    searchKeywords: ['yazılım', 'bilişim', 'ajans', 'dijital pazarlama', 'yazılım ajansı', 'web tasarım'],
  },
  furniture: {
    key: 'furniture',
    label: 'Mobilya & Ev Dekorasyon',
    emoji: '🛋️',
    iconName: 'Armchair',
    accent: '#854D0E',
    overpassFilter: '[shop~furniture|interior_decoration]',
    averageCatchmentRadius: 1500,
    idealDensityPerKm2: 4,
    isPopularTop8: false,
    searchKeywords: ['mobilya', 'dekorasyon', 'koltuk', 'yatak', 'masa', 'ev eşyası'],
  },
  electronics: {
    key: 'electronics',
    label: 'Elektronik & Telefon Tamiri',
    emoji: '📱',
    iconName: 'Smartphone',
    accent: '#4F46E5',
    overpassFilter: '[shop~electronics|mobile_phone]',
    averageCatchmentRadius: 700,
    idealDensityPerKm2: 8,
    isPopularTop8: false,
    searchKeywords: ['telefon', 'elektronik', 'tamir', 'cep telefonu', 'bilgisayar tamiri', 'aksesuar'],
  },
};

export const QUICK_LOCATION_PRESETS: QuickLocationPreset[] = [
  {
    id: 'ist-kadikoy-moda',
    name: 'Kadıköy / Moda',
    city: 'İstanbul',
    district: 'Kadıköy',
    lat: 40.9875,
    lng: 29.0289,
    zoom: 15,
    description: 'Yoğun yaya trafiği, genç & yaratıcı kitle',
  },
  {
    id: 'ist-besiktas-carsi',
    name: 'Beşiktaş / Çarşı',
    city: 'İstanbul',
    district: 'Beşiktaş',
    lat: 41.0428,
    lng: 29.0069,
    zoom: 15,
    description: 'Üniversite ve iş merkezi kesişimi',
  },
  {
    id: 'ist-sisli-nisantasi',
    name: 'Şişli / Nişantaşı',
    city: 'İstanbul',
    district: 'Şişli',
    lat: 41.0531,
    lng: 28.9928,
    zoom: 15,
    description: 'Yüksek alım gücü ve butik konseptler',
  },
  {
    id: 'ank-cankaya-tunali',
    name: 'Çankaya / Tunalı Hilmi',
    city: 'Ankara',
    district: 'Çankaya',
    lat: 39.9022,
    lng: 32.8601,
    zoom: 15,
    description: 'Bürokrasi, elçilikler ve sosyal yaşam merkezi',
  },
  {
    id: 'izm-karsiyaka-carsi',
    name: 'Karşıyaka / Çarşı',
    city: 'İzmir',
    district: 'Karşıyaka',
    lat: 38.4593,
    lng: 27.1124,
    zoom: 15,
    description: 'Kıyı şeridi ve yoğun yerel ticaret',
  },
  {
    id: 'ant-muratpasa-lara',
    name: 'Muratpaşa / Lara',
    city: 'Antalya',
    district: 'Muratpaşa',
    lat: 36.8584,
    lng: 30.7588,
    zoom: 14,
    description: 'Turizm, yabancı nüfus ve premium hizmetler',
  },
  {
    id: 'bur-nilufer-ozluce',
    name: 'Nilüfer / Özlüce',
    city: 'Bursa',
    district: 'Nilüfer',
    lat: 40.2198,
    lng: 28.9189,
    zoom: 14,
    description: 'Yeni nesil gastronomi ve modern konut bölgesi',
  },
];

export const RADAR_DEFAULT_CENTER = {
  lat: 40.9875,
  lng: 29.0289,
  zoom: 15,
};

export const RADAR_DEFAULT_RADIUS_METERS = 500;
